"use strict";
const STORAGE_KEY = "jisen-ceramics-label-maker-v1";
const API_KEY_SESSION = "jisen-gemini-key-session";
const API_KEY_LOCAL = "jisen-gemini-key-remembered";
const Pricing = globalThis.PricingAssistant;
const Image = globalThis.ImageAnalysis;
const TEMPLATE_NAMES={STANDARD:"己森标准", "JISEN SELECT":"己森精选", "JISEN ARCHIVE":"己森典藏"};
const DEFAULT_OPTIONS = {
  kiln:["備前焼","信楽焼","常滑焼","丹波焼","越前焼","瀬戸焼","九谷焼","有田焼","伊万里","日本中古","その他","不明"],
  itemType:["茶碗","湯呑","酒呑","徳利","急須","小皿","皿","鉢","花器","壺","甕","食器","茶器","酒器","装飾器","その他"],
  period:["昭和前期頃","昭和中期頃","昭和後期頃","平成頃","現代","年代不詳"],
  technique:["無釉焼締","自然釉","灰釉","施釉","朱泥","染付","色絵","金彩","青磁","上絵","焼締","窯変","その他"],
  accessories:["なし","共箱","木箱","栞","布","共箱・栞","その他"],
  condition:["良好","使用感あり","経年感あり","小傷あり","小欠けあり","貫入あり","補修あり","詳細はスタッフまで"]
};
const FIELD_NAMES={kiln:"窑口",itemType:"器型",period:"年代",technique:"工艺",accessories:"附件",condition:"品相"};
const FLAGS=["showPeriod","showTechnique","showArtist","showAccessories","showCondition","showSku"];
const FLAG_NAMES=["显示年代","显示工艺","显示作家","显示附件","显示品相","显示 SKU"];
const DEMOS=[
  ["備前焼","酒呑","昭和後期頃","無釉焼締","JISEN SELECT","JC-0001",298],
  ["信楽焼","茶碗","昭和後期頃","自然釉","STANDARD","JC-0002",198],
  ["常滑焼","急須","昭和後期頃","朱泥","JISEN SELECT","JC-0003",398],
  ["丹波焼","酒器","昭和中期頃","自然釉","JISEN SELECT","JC-0004",298],
  ["越前焼","花器","年代不詳","焼締","STANDARD","JC-0005",198],
  ["瀬戸焼","小皿","昭和後期頃","施釉","STANDARD","JC-0006",128],
  ["九谷焼","小皿","昭和後期頃","色絵・金彩","JISEN SELECT","JC-0007",268],
  ["有田焼","湯呑","昭和後期頃","染付","STANDARD","JC-0008",168]
];
const $=id=>document.getElementById(id);
const freshId=()=>globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const blankItem=()=>{const id=freshId();return {id,recordId:id,captureStatus:"READY",photoCount:0,templateType:"STANDARD",kiln:"",itemType:"",customItemName:"",period:"",technique:"",artist:"",studio:"",accessories:"",condition:"",sku:"",price:"",note:"",...Object.fromEntries(FLAGS.map(key=>[key,true])),...Pricing.defaultItem(),...Image.defaultItem()}};
const defaults=()=>({items:DEMOS.map(d=>({...blankItem(),kiln:d[0],itemType:d[1],period:d[2],technique:d[3],templateType:d[4],sku:d[5],price:String(d[6])})),options:structuredClone(DEFAULT_OPTIONS),cutLines:true,currencySymbol:true,pricingSettings:Pricing.defaultSettings(),aiSettings:{enabled:false,grounding:false,model:"",rememberKey:false}});
const safeText=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
const normalizeOptions=input=>Object.fromEntries(Object.keys(DEFAULT_OPTIONS).map(key=>[key,Array.isArray(input?.[key])?input[key].filter(v=>typeof v==="string"&&v.trim()).map(v=>v.trim()).slice(0,200):[...DEFAULT_OPTIONS[key]]]));
function normalizeItem(input){const item=blankItem();if(!input||typeof input!=="object")return item;for(const key of ["templateType","kiln","itemType","customItemName","period","technique","artist","studio","accessories","condition","sku","price","note"]){item[key]=String(input[key]??"").slice(0,500)}for(const key of FLAGS)item[key]=input[key]!==false;Object.assign(item,Pricing.normalizeItem(input),Image.normalizeItem(input));item.id=typeof input.id==="string"&&input.id?input.id:freshId();item.recordId=typeof input.recordId==="string"&&input.recordId?input.recordId:item.id;item.captureStatus=["DRAFT","READY","REVIEW","EXPORTED","APPROVED"].includes(input.captureStatus)?input.captureStatus:"READY";item.photoCount=Math.max(0,Number(input.photoCount)||0);for(const key of ["batchId","deviceId","createdAt","updatedAt","exportedAt"])item[key]=String(input[key]??"");item.ownerReviewRequired=input.ownerReviewRequired===true;item.aiResearchResult=input.aiResearchResult&&typeof input.aiResearchResult==="object"?input.aiResearchResult:null;if(!["STANDARD","JISEN SELECT","JISEN ARCHIVE"].includes(item.templateType))item.templateType="STANDARD";return item}
function normalizeState(input){if(!input||typeof input!=="object"||!Array.isArray(input.items))throw Error("JSON 缺少商品列表 items。");return {items:input.items.slice(0,1000).map(normalizeItem),options:normalizeOptions(input.options),cutLines:input.cutLines!==false,currencySymbol:input.currencySymbol!==false,pricingSettings:Pricing.normalizeSettings(input.pricingSettings),aiSettings:{enabled:input.aiSettings?.enabled===true,grounding:input.aiSettings?.grounding===true,model:String(input.aiSettings?.model??"").slice(0,100),rememberKey:input.aiSettings?.rememberKey===true}}}
let state;try{const saved=localStorage.getItem(STORAGE_KEY);state=saved?normalizeState(JSON.parse(saved)):defaults()}catch(error){console.warn("Could not load saved data",error);state=defaults();alert("本地数据读取失败，已载入演示数据。请检查或导入备份 JSON。")}
let page=0;let expandedId=null;const selected=new Set();
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$("saveStatus").textContent=`已保存 · ${new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`;return true}catch(error){console.error(error);$("saveStatus").textContent="保存失败，请导出 JSON 备份";return false}}
function dropdown(item,key){const choices=state.options[key];const value=key==="itemType"&&item.itemType==="自定义"?"自定义":item[key];const isCustom=!!value&&!choices.includes(value)||value==="自定义";const displayed=isCustom?"自定义":value;return `<select data-id="${safeText(item.id)}" data-field="${key}" aria-label="${FIELD_NAMES[key]}"><option value="">请选择</option>${choices.map(option=>`<option value="${safeText(option)}" ${displayed===option?"selected":""}>${safeText(option)}</option>`).join("")}<option value="自定义" ${isCustom?"selected":""}>自定义</option></select>${isCustom?`<input class="custom-input" type="text" data-id="${safeText(item.id)}" data-custom="${key}" value="${safeText(key==="itemType"?item.customItemName:item[key]==="自定义"?"":item[key])}" placeholder="输入自定义${FIELD_NAMES[key]}">`:""}`}
function techniquePicker(item){const parts=item.technique.split("・").map(v=>v.trim()).filter(Boolean);const custom=parts.filter(v=>!state.options.technique.includes(v));return `<details class="technique-picker"><summary title="${safeText(item.technique)}">${safeText(item.technique||"选择工艺")}</summary><div class="technique-menu">${state.options.technique.map(value=>`<label><input type="checkbox" data-tech="${safeText(value)}" data-id="${safeText(item.id)}" ${parts.includes(value)?"checked":""}>${safeText(value)}</label>`).join("")}<input type="text" data-tech-custom="${safeText(item.id)}" value="${safeText(custom.join("・"))}" placeholder="自定义，用・分隔"></div></details>`}
function rowHtml(item){return `<tr data-row="${safeText(item.id)}"><td><input type="checkbox" data-select="${safeText(item.id)}" ${selected.has(item.id)?"checked":""} aria-label="选择 ${safeText(item.sku||"商品")}"></td><td><select class="template-select" data-id="${safeText(item.id)}" data-field="templateType">${["STANDARD","JISEN SELECT","JISEN ARCHIVE"].map(v=>`<option value="${v}" ${v===item.templateType?"selected":""}>${TEMPLATE_NAMES[v]}</option>`).join("")}</select></td><td>${dropdown(item,"kiln")}</td><td>${dropdown(item,"itemType")}</td><td>${dropdown(item,"period")}</td><td>${techniquePicker(item)}</td><td><input type="text" data-id="${safeText(item.id)}" data-field="artist" value="${safeText(item.artist)}" placeholder="选填"></td><td>${dropdown(item,"accessories")}</td><td>${dropdown(item,"condition")}</td><td><input class="sku-input" type="text" data-id="${safeText(item.id)}" data-field="sku" value="${safeText(item.sku)}"></td><td><input class="price-input" type="number" min="0" step="0.01" data-id="${safeText(item.id)}" data-field="price" value="${safeText(item.price)}"></td><td class="suggestion">¥${safeText(item.suggestedPrice)}</td><td><div class="row-actions"><button data-image="${safeText(item.id)}">图片分析</button><button data-pricing="${safeText(item.id)}">定价</button><button data-research="${safeText(item.id)}" class="${item.researchRequired?"research-needed":"research-idle"}" ${item.researchRequired?"":"disabled"} title="${item.researchRequired?"需要进一步调查":"普通商品无需 AI；如需深查，请在定价中勾选"}">AI</button></div></td><td><div class="row-actions"><button data-action="detail" data-id="${safeText(item.id)}" title="更多字段与显示控制">更多</button><button data-action="copy" data-id="${safeText(item.id)}">复制</button><button data-action="up" data-id="${safeText(item.id)}" title="上移">↑</button><button data-action="down" data-id="${safeText(item.id)}" title="下移">↓</button><button data-action="delete" data-id="${safeText(item.id)}" title="删除">×</button></div></td></tr>${expandedId===item.id?`<tr class="details-row"><td colspan="14"><div class="detail-grid"><label>工作室 / 窑房<input type="text" data-id="${safeText(item.id)}" data-field="studio" value="${safeText(item.studio)}"></label><label>备注（仅保存，不印在价签）<input type="text" data-id="${safeText(item.id)}" data-field="note" value="${safeText(item.note)}"></label><span></span><div class="checks">${FLAGS.map((key,i)=>`<label><input type="checkbox" data-id="${safeText(item.id)}" data-flag="${key}" ${item[key]?"checked":""}>${FLAG_NAMES[i]}</label>`).join("")}</div></div></td></tr>`:""}`}
let reviewOnly=false;
function renderRows(){state.items.forEach(item=>Pricing.applyCalculation(item,state.pricingSettings));const shown=reviewOnly?state.items.filter(item=>item.captureStatus==="REVIEW"):state.items;$("itemRows").innerHTML=shown.map(rowHtml).join("");for(const item of shown){const row=[...$("itemRows").querySelectorAll("tr[data-row]")].find(el=>el.dataset.row===item.id);const cell=row?.lastElementChild;if(!cell)continue;if(item.photoCount)cell.insertAdjacentHTML("beforeend",`<button data-photo-view="${safeText(item.recordId)}">📷 ${item.photoCount}</button>`);if(item.captureStatus==="REVIEW")cell.insertAdjacentHTML("beforeend",`<button data-review-open="${safeText(item.recordId)}">老板审核</button>`)}$("itemCount").textContent=`${shown.length} / ${state.items.length} 件`;$("selectAll").checked=shown.length>0&&shown.every(item=>selected.has(item.id))}
function updatePricingCell(item){Pricing.applyCalculation(item,state.pricingSettings);const row=[...$("itemRows").querySelectorAll("tr[data-row]")].find(el=>el.dataset.row===item.id);if(!row)return;row.querySelector(".suggestion").textContent=`¥${item.suggestedPrice}`;const button=row.querySelector("[data-research]");button.disabled=!item.researchRequired;button.className=item.researchRequired?"research-needed":"research-idle"}
function formattedPrice(value){if(value===""||!Number.isFinite(Number(value))||Number(value)<0)return "";return `${state.currencySymbol?"¥":""}${new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2}).format(Number(value))}`}
function labelHtml(item){const title=[item.kiln,item.itemType==="自定义"?item.customItemName:item.itemType].filter(Boolean).join("　");const meta=[];if(item.showPeriod&&item.period&&item.period!=="自定义")meta.push(item.period);if(item.showTechnique&&item.technique)meta.push(item.technique);if(item.showArtist&&item.artist)meta.push(`${item.artist} 作`);else if(item.showArtist&&item.studio)meta.push(item.studio);if(item.showAccessories&&item.accessories&&item.accessories!=="なし"&&item.accessories!=="自定义")meta.push(item.accessories);if(item.showCondition&&item.condition&&item.condition!=="自定义")meta.push(item.condition);const mark=item.templateType==="STANDARD"?"":TEMPLATE_NAMES[item.templateType]||"";return `<article class="label ${item.templateType==="JISEN ARCHIVE"?"archive":item.templateType==="JISEN SELECT"?"select":"standard"} ${meta.length>3?"dense":""}"><div class="brand">己森 · 日本の器</div><div class="name">${safeText(title)}</div>${meta.length?`<div class="meta">${meta.map(v=>`<div>${safeText(v)}</div>`).join("")}</div>`:""}<div class="mark">${safeText(mark)}</div><div class="bottom"><span class="sku">${item.showSku?safeText(item.sku):""}</span><span class="price">${safeText(formattedPrice(item.price))}</span></div></article>`}
function paperHtml(items){return `<div class="paper ${state.cutLines?"":"no-cuts"}">${items.map(labelHtml).join("")}</div>`}
function renderPreview(){const printable=state.items.filter(item=>item.captureStatus!=="REVIEW"&&item.captureStatus!=="DRAFT");const pages=Math.max(1,Math.ceil(printable.length/18));page=Math.min(page,pages-1);const chunks=Array.from({length:pages},(_,i)=>printable.slice(i*18,(i+1)*18));$("screenPaper").outerHTML=paperHtml(chunks[page]).replace("<div class=\"paper", "<div id=\"screenPaper\" class=\"paper");$("printPages").innerHTML=chunks.map(paperHtml).join("");$("pageIndicator").textContent=`第 ${page+1} / ${pages} 页`;$("prevPage").disabled=page===0;$("nextPage").disabled=page>=pages-1;$("cutLines").checked=state.cutLines;$("currencySymbol").checked=state.currencySymbol}
function refresh(){renderRows();renderPreview();persist()}
function itemFor(id){return state.items.find(item=>item.id===id)}
$("itemRows").addEventListener("input",event=>{const el=event.target;const item=itemFor(el.dataset.id||el.dataset.techCustom);if(!item)return;if(el.dataset.custom){if(el.dataset.custom==="itemType"){item.itemType="自定义";item.customItemName=el.value}else item[el.dataset.custom]=el.value}else if(el.dataset.field){item[el.dataset.field]=el.value}else if(el.dataset.techCustom){const checked=[...el.closest(".technique-menu").querySelectorAll("[data-tech]:checked")].map(x=>x.dataset.tech);item.technique=[...checked,...el.value.split("・").map(x=>x.trim()).filter(Boolean)].join("・");el.closest("details").querySelector("summary").textContent=item.technique||"选择工艺"}else return;updatePricingCell(item);renderPreview();persist()});
$("itemRows").addEventListener("change",event=>{const el=event.target;if(el.dataset.select){el.checked?selected.add(el.dataset.select):selected.delete(el.dataset.select);$("selectAll").checked=state.items.length>0&&state.items.every(item=>selected.has(item.id));return}const item=itemFor(el.dataset.id);if(!item)return;if(el.dataset.flag){item[el.dataset.flag]=el.checked;updatePricingCell(item);renderPreview();persist();return}if(el.dataset.tech){const menu=el.closest(".technique-menu");item.technique=[...menu.querySelectorAll("[data-tech]:checked")].map(x=>x.dataset.tech).concat(menu.querySelector("[data-tech-custom]").value.split("・").map(x=>x.trim()).filter(Boolean)).join("・");el.closest("details").querySelector("summary").textContent=item.technique||"选择工艺";updatePricingCell(item);renderPreview();persist();return}if(el.dataset.field){if(el.value==="自定义"){item[el.dataset.field]="自定义";if(el.dataset.field==="itemType")item.customItemName="";renderRows();const row=[...$("itemRows").querySelectorAll("tr[data-row]")].find(x=>x.dataset.row===item.id);row?.querySelector(`[data-custom="${el.dataset.field}"]`)?.focus()}else{item[el.dataset.field]=el.value;if(el.dataset.field==="itemType")item.customItemName="";if(el.tagName==="SELECT")renderRows()}updatePricingCell(item);renderPreview();persist()}});
$("itemRows").addEventListener("click",event=>{const imageButton=event.target.closest("button[data-image]");if(imageButton){openImageAnalysis(imageButton.dataset.image);return}const pricingButton=event.target.closest("button[data-pricing]");if(pricingButton){openPricing(pricingButton.dataset.pricing);return}const researchButton=event.target.closest("button[data-research]");if(researchButton){openResearch(researchButton.dataset.research);return}const button=event.target.closest("button[data-action]");if(!button)return;const index=state.items.findIndex(item=>item.id===button.dataset.id);if(index<0)return;const item=state.items[index];switch(button.dataset.action){case"detail":expandedId=expandedId===item.id?null:item.id;renderRows();return;case"copy":state.items.splice(index+1,0,{...item,id:freshId(),recordId:freshId(),photoCount:0});break;case"up":if(index>0)[state.items[index-1],state.items[index]]=[state.items[index],state.items[index-1]];break;case"down":if(index<state.items.length-1)[state.items[index+1],state.items[index]]=[state.items[index],state.items[index+1]];break;case"delete":state.items.splice(index,1);selected.delete(item.id);break}refresh()});
$("selectAll").addEventListener("change",event=>{selected.clear();if(event.target.checked)state.items.forEach(item=>selected.add(item.id));renderRows()});
$("addBtn").onclick=()=>{state.items.push(blankItem());page=Math.floor((state.items.length-1)/18);refresh()};
$("copyLastBtn").onclick=()=>{const previous=state.items.at(-1);const id=freshId();state.items.push(previous?{...previous,id,recordId:id,photoCount:0,captureStatus:"READY",sku:"",price:""}:blankItem());page=Math.floor((state.items.length-1)/18);refresh()};
$("deleteSelectedBtn").onclick=()=>{if(!selected.size)return;if(!confirm(`删除所选 ${selected.size} 件商品？`))return;state.items=state.items.filter(item=>!selected.has(item.id));selected.clear();refresh()};
$("prevPage").onclick=()=>{page--;renderPreview()};$("nextPage").onclick=()=>{page++;renderPreview()};
$("cutLines").onchange=event=>{state.cutLines=event.target.checked;renderPreview();persist()};$("currencySymbol").onchange=event=>{state.currencySymbol=event.target.checked;renderPreview();persist()};
$("saveBtn").onclick=()=>{if(persist())alert("已保存到当前浏览器。")};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({version:2,...state},null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`JISEN-CERAMICS-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
$("importBtn").onclick=()=>$("importFile").click();$("importFile").onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{const imported=normalizeState(JSON.parse(await file.text()));if(!confirm(`导入 ${imported.items.length} 件商品并替换当前数据？`))return;state=imported;page=0;selected.clear();expandedId=null;refresh();renderSettings();renderPricingSettings();alert("导入完成。")}catch(error){alert(`导入失败：${error.message}`)}finally{event.target.value=""}};
$("clearBtn").onclick=()=>{if(!confirm("确定清空全部商品和自定义选项吗？此操作不可撤销。"))return;if(!confirm("再次确认：所有本地商品和设置都将清空。建议先导出 JSON。"))return;state={items:[],options:structuredClone(DEFAULT_OPTIONS),cutLines:true,currencySymbol:true,pricingSettings:Pricing.defaultSettings(),aiSettings:{enabled:false,grounding:false,model:"",rememberKey:false}};sessionStorage.removeItem(API_KEY_SESSION);localStorage.removeItem(API_KEY_LOCAL);selected.clear();page=0;expandedId=null;refresh();renderSettings();renderPricingSettings()};
$("printBtn").onclick=()=>{renderPreview();window.print()};
function setView(settings){$("settingsView").hidden=!settings;$("editorView").hidden=settings;$("editorTab").classList.toggle("active",!settings);$("settingsTab").classList.toggle("active",settings);if(settings){renderSettings();renderPricingSettings()}}
$("settingsTab").onclick=()=>setView(true);$("editorTab").onclick=()=>setView(false);$("backBtn").onclick=()=>setView(false);
function renderSettings(){ $("settingsGroups").innerHTML=Object.keys(DEFAULT_OPTIONS).map(key=>`<section class="settings-card" data-group="${key}"><h3>${FIELD_NAMES[key]}</h3><div class="option-list">${state.options[key].map((value,index)=>`<div class="option-row"><input type="text" data-option="${key}" data-index="${index}" value="${safeText(value)}" aria-label="${FIELD_NAMES[key]}选项 ${index+1}"><button data-remove="${key}" data-index="${index}" aria-label="删除 ${safeText(value)}">删除</button></div>`).join("")}</div><div class="add-option"><input type="text" placeholder="新增${FIELD_NAMES[key]}选项" data-new="${key}"><button data-add="${key}">添加</button></div><button class="restore" data-restore="${key}">恢复默认</button></section>`).join("")}
$("settingsGroups").addEventListener("change",event=>{const el=event.target;if(!el.dataset.option)return;const values=state.options[el.dataset.option];const index=Number(el.dataset.index);const value=el.value.trim();if(!value||values.some((v,i)=>i!==index&&v===value)){alert("选项不能为空或重复。");renderSettings();return}values[index]=value;persist();renderRows();renderPreview()});
$("settingsGroups").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.dataset.add){const key=button.dataset.add;const input=button.closest(".settings-card").querySelector("[data-new]");const value=input.value.trim();if(!value||state.options[key].includes(value)){alert("请输入未存在的选项。");return}state.options[key].push(value)}else if(button.dataset.remove){state.options[button.dataset.remove].splice(Number(button.dataset.index),1)}else if(button.dataset.restore){if(!confirm(`恢复${FIELD_NAMES[button.dataset.restore]}的默认选项？`))return;state.options[button.dataset.restore]=[...DEFAULT_OPTIONS[button.dataset.restore]]}else return;persist();renderSettings();renderRows();renderPreview()});

const IDENTITY_LABELS={A_CONFIRMED:"A｜确认",B_PROBABLE:"B｜高概率",C_STYLE:"C｜风格判断",D_UNKNOWN:"D｜未知"};
let activePricingId=null,activeResearchId=null;
const money=value=>`¥${new Intl.NumberFormat("zh-CN",{maximumFractionDigits:2}).format(Number(value)||0)}`;
function openPricing(id){if(!itemFor(id))return;activePricingId=id;renderPricingDialog();$("pricingDialog").showModal()}
function renderPricingDialog(){const item=itemFor(activePricingId);if(!item)return;const calc=Pricing.applyCalculation(item,state.pricingSettings);$("pricingTitle").textContent=`辅助定价 · ${item.sku||"未编号"}`;
  const factorRows=state.pricingSettings.factors.map(f=>`<label class="factor-row"><input type="checkbox" data-factor="${safeText(f.id)}" ${item.pricingFactors.includes(f.id)?"checked":""}><span>${safeText(f.label)} <small>+${f.steps} 档${f.identityRelated?" · 需 A/B 身份":""}</small></span></label>`).join("");
  const conditionOptions=Object.entries(state.pricingSettings.conditionAdjustments).map(([name,value])=>`<option value="${safeText(name)}" ${item.condition===name?"selected":""}>${safeText(name)}（${value===null?"人工审核":`${value} 档`}）</option>`).join("");
  $("pricingContent").innerHTML=`<div class="pricing-grid"><section><h3>身份与因素</h3><label class="stacked">身份可信度<select id="identityConfidence">${Object.entries(IDENTITY_LABELS).map(([v,label])=>`<option value="${v}" ${item.identityConfidence===v?"selected":""}>${label}</option>`).join("")}</select></label><p class="small-note">C 类建议在对外标签使用“○○系”；D 类建议使用“日本中古陶器”。这里只提示，不自动改写价签。</p><div class="factor-list">${factorRows}</div><label class="stacked">品相<select id="pricingCondition"><option value="">未填写</option>${conditionOptions}</select></label><label class="stacked">底款 / 箱书备注<input id="bottomMarkNote" type="text" value="${safeText(item.bottomMarkNote)}"></label><div class="flag-list"><label><input type="checkbox" data-pricing-flag="identityConflict" ${item.identityConflict?"checked":""}>身份存在冲突</label><label><input type="checkbox" data-pricing-flag="possibleCollectible" ${item.possibleCollectible?"checked":""}>可能为收藏级</label><label><input type="checkbox" data-pricing-flag="manualDeepResearch" ${item.manualDeepResearch?"checked":""}>需要深查</label></div></section><section><h3>规则结果</h3><div class="calculation"><div>基础价 <strong>${money(calc.pricingBase)}</strong></div><div>身份 / 附加因素 <strong>+${calc.pricingScore} 档</strong></div><div>品相 <strong>${calc.review?"人工审核":`${calc.conditionAdjustment} 档`}</strong></div><div class="suggested">建议价 <strong>${money(calc.suggestedPrice)}</strong></div></div><p class="small-note">计算：基础阶梯第 ${calc.baseIndex+1} 档 + ${calc.pricingScore} 档 ${calc.review?"；品相需人工判断":`${calc.conditionAdjustment} 档`}。${calc.ignored.length?`身份相关的 ${calc.ignored.map(f=>safeText(f.label)).join("、")} 未计入。`:""}${calc.baseUnrounded!==calc.pricingBase?`原始器型基础价 ${money(calc.baseUnrounded)} 对齐最近阶梯 ${money(calc.pricingBase)}。`:""}</p><p><strong>建议模板：</strong>${TEMPLATE_NAMES[calc.templateSuggestion]} <button id="applyTemplate">应用建议模板</button></p><div class="research-status">${calc.researchRequired?`<strong>需要进一步调查</strong><ul>${calc.researchReasons.map(r=>`<li>${safeText(r)}</li>`).join("")}</ul>`:"普通商品：无需 AI 调查。"}</div><button id="fromPricingResearch" class="${calc.researchRequired?"research-needed":""}" ${calc.researchRequired?"":"disabled"}>AI 辅助调查</button><div class="final-adopt"><label class="stacked">最终售价（人工填写）<input id="pricingFinalPrice" type="number" min="0" step="0.01" value="${safeText(item.finalPrice)}"></label><button id="adoptPricingPrice" class="primary">采用最终价格</button><p class="small-note">只有点击“采用最终价格”，才会写入原售价字段。</p></div></section></div>`}
$("closePricing").onclick=()=>$("pricingDialog").close();
$("pricingContent").addEventListener("change",event=>{const item=itemFor(activePricingId);if(!item)return;const el=event.target;if(el.id==="identityConfidence")item.identityConfidence=el.value;else if(el.id==="pricingCondition")item.condition=el.value;else if(el.dataset.factor){const set=new Set(item.pricingFactors);el.checked?set.add(el.dataset.factor):set.delete(el.dataset.factor);item.pricingFactors=[...set]}else if(el.dataset.pricingFlag)item[el.dataset.pricingFlag]=el.checked;else if(el.id==="pricingFinalPrice")item.finalPrice=el.value;else if(el.id==="bottomMarkNote")item.bottomMarkNote=el.value;else return;updatePricingCell(item);renderRows();renderPreview();persist();if(el.id!=="pricingFinalPrice")renderPricingDialog()});
$("pricingContent").addEventListener("input",event=>{const item=itemFor(activePricingId);if(!item)return;if(event.target.id==="pricingFinalPrice")item.finalPrice=event.target.value;if(event.target.id==="bottomMarkNote")item.bottomMarkNote=event.target.value;persist()});
$("pricingContent").addEventListener("click",event=>{const item=itemFor(activePricingId);if(!item)return;if(event.target.id==="applyTemplate"){item.templateType=Pricing.calculate(item,state.pricingSettings).templateSuggestion;refresh();renderPricingDialog()}else if(event.target.id==="fromPricingResearch"){$("pricingDialog").close();openResearch(item.id)}else if(event.target.id==="adoptPricingPrice"){const value=Number(item.finalPrice);if(item.finalPrice===""||!Number.isFinite(value)||value<0){alert("请输入有效的最终售价。");return}item.price=String(value);refresh();renderPricingDialog()}});

function getApiKey(){try{return state.aiSettings.rememberKey?localStorage.getItem(API_KEY_LOCAL)||"":sessionStorage.getItem(API_KEY_SESSION)||""}catch{return ""}}
function storeApiKey(value){try{if(state.aiSettings.rememberKey){localStorage.setItem(API_KEY_LOCAL,value);sessionStorage.removeItem(API_KEY_SESSION)}else{sessionStorage.setItem(API_KEY_SESSION,value);localStorage.removeItem(API_KEY_LOCAL)}}catch{alert("API Key 保存失败，请检查浏览器存储权限。")}}
function renderPricingSettings(){const cfg=state.pricingSettings;$("pricingSettings").innerHTML=`<section class="settings-card pricing-settings"><h3>规则定价</h3><label class="stacked">统一价格阶梯（逗号分隔，升序）<textarea id="priceStepsSetting" rows="2">${safeText(cfg.priceSteps.join(", "))}</textarea></label><label class="stacked">未知器型默认基础价<input id="fallbackBaseSetting" type="number" min="1" value="${cfg.fallbackBase}"></label><h4>器型基础价</h4><div class="config-list">${Object.entries(cfg.basePrices).map(([type,price])=>`<div class="config-row"><span>${safeText(type)}</span><input type="number" min="1" data-base-type="${safeText(type)}" value="${price}"></div>`).join("")}</div><div class="add-option"><input id="newBaseType" type="text" placeholder="新器型"><input id="newBasePrice" type="number" min="1" placeholder="基础价"><button id="addBase">添加</button></div><h4>加价因素</h4><div class="config-list">${cfg.factors.map(f=>`<div class="factor-setting"><input type="text" data-factor-label="${safeText(f.id)}" value="${safeText(f.label)}" aria-label="因素名称"><input type="number" min="0" max="10" data-factor-steps="${safeText(f.id)}" value="${f.steps}" aria-label="档数"><label><input type="checkbox" data-factor-identity="${safeText(f.id)}" ${f.identityRelated?"checked":""}>身份相关</label></div>`).join("")}</div><h4>品相调整（空白代表人工审核）</h4><div class="config-list">${Object.entries(cfg.conditionAdjustments).map(([name,value])=>`<div class="config-row"><span>${safeText(name)}</span><input type="number" max="0" min="-10" data-condition-name="${safeText(name)}" value="${value??""}" placeholder="人工审核"></div>`).join("")}</div><button id="restorePricing">恢复默认定价规则</button></section><section class="settings-card pricing-settings"><h3>AI Research · Gemini API</h3><label class="switch"><input id="apiEnabled" type="checkbox" ${state.aiSettings.enabled?"checked":""}>Gemini API：ON（默认 OFF）</label><label class="stacked">模型名称<input id="geminiModel" type="text" value="${safeText(state.aiSettings.model)}" placeholder="输入当前可用的 Gemini 模型 ID"></label><label class="stacked">API Key<input id="geminiKey" type="password" autocomplete="off" value="${safeText(getApiKey())}" placeholder="仅本机使用"></label><label class="switch"><input id="rememberKey" type="checkbox" ${state.aiSettings.rememberKey?"checked":""}>在本机记住 API Key（否则仅本次会话）</label><label class="switch"><input id="groundingEnabled" type="checkbox" ${state.aiSettings.grounding?"checked":""}>使用 Google Search Grounding</label><p class="small-note">Key 不写入商品 JSON。仅在你点击“调用 Gemini”时发送给 Google。无 API 模式始终可用；本地文件环境的浏览器可能限制跨域请求。</p></section>`}
$("pricingSettings").addEventListener("change",event=>{const el=event.target,cfg=state.pricingSettings;if(el.id==="priceStepsSetting"){const values=el.value.split(/[,，\s]+/).filter(Boolean).map(Number);if(values.length<2||values.some((v,i)=>!Number.isFinite(v)||v<=0||(i&&v<=values[i-1]))){alert("阶梯至少两档，且必须为正数并严格升序。");renderPricingSettings();return}cfg.priceSteps=values}else if(el.id==="fallbackBaseSetting"){if(Number(el.value)<=0)return;cfg.fallbackBase=Number(el.value)}else if(el.dataset.baseType){if(Number(el.value)<=0)return;cfg.basePrices[el.dataset.baseType]=Number(el.value)}else if(el.dataset.factorLabel){const f=cfg.factors.find(x=>x.id===el.dataset.factorLabel);if(f&&el.value.trim())f.label=el.value.trim()}else if(el.dataset.factorSteps){const f=cfg.factors.find(x=>x.id===el.dataset.factorSteps);if(f)f.steps=Math.max(0,Math.min(10,Number(el.value)||0))}else if(el.dataset.factorIdentity){const f=cfg.factors.find(x=>x.id===el.dataset.factorIdentity);if(f)f.identityRelated=el.checked}else if(el.dataset.conditionName){cfg.conditionAdjustments[el.dataset.conditionName]=el.value===""?null:Math.min(0,Number(el.value)||0)}else if(el.id==="apiEnabled")state.aiSettings.enabled=el.checked;else if(el.id==="groundingEnabled")state.aiSettings.grounding=el.checked;else if(el.id==="geminiModel")state.aiSettings.model=el.value.trim();else if(el.id==="geminiKey")storeApiKey(el.value.trim());else if(el.id==="rememberKey"){const old=getApiKey();state.aiSettings.rememberKey=el.checked;storeApiKey(old)}else return;state.pricingSettings=Pricing.normalizeSettings(cfg);renderRows();renderPreview();persist()});
$("pricingSettings").addEventListener("click",event=>{const id=event.target.id;if(id==="addBase"){const name=$("newBaseType").value.trim(),price=Number($("newBasePrice").value);if(!name||!Number.isFinite(price)||price<=0){alert("请输入器型和有效基础价。");return}state.pricingSettings.basePrices[name]=price}else if(id==="restorePricing"){if(!confirm("恢复默认定价规则？"))return;state.pricingSettings=Pricing.defaultSettings()}else return;renderPricingSettings();renderRows();renderPreview();persist()});

function researchValue(value){if(value==null||value==="")return "未提供";return typeof value==="string"?value:JSON.stringify(value,null,2)}
function researchResultHtml(result){if(!result)return "";const fields=[["identityAssessment","身份判断"],["artistAssessment","作者调查"],["marketEvidence","市场依据"],["soldComparables","实际成交对比"],["askingPrices","挂牌价格"],["risks","风险"],["recommendedRetailRange","AI 调查建议区间"],["confidence","AI 信心"],["sources","来源"]];return `<section class="research-result"><h3>已保存的调查结果</h3>${fields.map(([key,label])=>`<div><strong>${label}</strong><pre>${safeText(researchValue(result[key]))}</pre></div>`).join("")}</section>`}
function openResearch(id){const item=itemFor(id);if(!item)return;activeResearchId=id;renderResearch();$("researchDialog").showModal()}
function renderResearch(){const item=itemFor(activeResearchId);if(!item)return;const calc=Pricing.applyCalculation(item,state.pricingSettings);$("researchTitle").textContent=`AI 辅助调查 · ${item.sku||"未编号"}`;const prompt=Pricing.makePrompt(item,calc);$("researchContent").innerHTML=`<p class="small-note">仅供调查。作者、窑口和最终售价均需人工核对。规则建议：<strong>${money(calc.suggestedPrice)}</strong>。${calc.researchReasons.map(safeText).join("；")}</p><textarea id="researchPrompt" rows="15" readonly>${safeText(prompt)}</textarea><div class="research-actions"><button id="copyPrompt">复制调查 Prompt</button><button id="openGemini">打开 Gemini</button><button id="callGemini" class="${state.aiSettings.enabled?"research-needed":""}" ${state.aiSettings.enabled?"":"disabled"}>调用 Gemini API</button></div><p id="researchStatus" role="status">${state.aiSettings.enabled?"API 模式已开启；点击调用才会发送商品资料。":"当前为无 API 模式。复制 Prompt 后自行调查。"}</p>${researchResultHtml(item.aiResearchResult)}<div class="final-adopt"><label class="stacked">最终售价（人工填写）<input id="researchFinalPrice" type="number" min="0" step="0.01" value="${safeText(item.finalPrice)}"></label><button id="adoptResearchPrice" class="primary">采用最终价格</button><p class="small-note">AI 调查结果不会自动写入价签售价。</p></div>`}
$("closeResearch").onclick=()=>$("researchDialog").close();
$("researchContent").addEventListener("input",event=>{if(event.target.id==="researchFinalPrice"){const item=itemFor(activeResearchId);if(item){item.finalPrice=event.target.value;persist()}}});
$("researchContent").addEventListener("click",async event=>{const id=event.target.id,item=itemFor(activeResearchId);if(!item)return;if(id==="copyPrompt"){const field=$("researchPrompt");try{await navigator.clipboard.writeText(field.value);$("researchStatus").textContent="Prompt 已复制。"}catch{field.select();const copied=document.execCommand("copy");$("researchStatus").textContent=copied?"Prompt 已复制。":"自动复制失败；请在文本框内手动复制。"}}else if(id==="openGemini"){window.open("https://gemini.google.com/app","_blank","noopener,noreferrer")}else if(id==="callGemini"){await callGemini(item)}else if(id==="adoptResearchPrice"){const value=Number(item.finalPrice);if(item.finalPrice===""||!Number.isFinite(value)||value<0){alert("请输入有效的最终售价。");return}item.price=String(value);refresh();renderResearch()}});
async function callGemini(item){const status=$("researchStatus"),button=$("callGemini");if(!state.aiSettings.enabled)return;const key=getApiKey(),model=state.aiSettings.model.trim().replace(/^models\//,"");if(!key||!model){status.textContent="请先在设置中填写模型名称和 API Key；也可复制 Prompt 手动查询。";return}button.disabled=true;status.textContent="正在调查，请稍候……";const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),60000);try{const body={contents:[{parts:[{text:Pricing.makePrompt(item,Pricing.calculate(item,state.pricingSettings))}]}]};if(state.aiSettings.grounding)body.tools=[{google_search:{}}];else body.generationConfig={responseMimeType:"application/json"};const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify(body),signal:controller.signal});if(!response.ok)throw Error(`HTTP ${response.status}`);const payload=await response.json();const candidate=payload.candidates?.[0];const raw=candidate?.content?.parts?.map(part=>part.text||"").join("").trim();if(!raw)throw Error("未返回可读取的调查文本");const cleaned=raw.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const parsed=JSON.parse(cleaned);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw Error("返回内容不是 JSON 对象");const grounded=candidate.groundingMetadata?.groundingChunks?.map(chunk=>chunk.web).filter(Boolean).map(web=>({title:web.title||"",url:web.uri||""}))||[];if(grounded.length)parsed.sources=[parsed.sources,grounded].filter(Boolean);parsed.researchedAt=new Date().toISOString();item.aiResearchResult=parsed;persist();renderResearch();$("researchStatus").textContent="调查结果已保存。请核对原始来源与商品身份。"}catch(error){console.warn("Gemini research failed",error);status.textContent=`API 调用失败（${error.message}）。请复制 Prompt 手动查询；本地定价与价签不受影响。`;button.disabled=false}finally{clearTimeout(timeout)}}

let activeImageId=null;
let imageSession=null; // File and data URL are memory-only; never serialized into state.
function openImageAnalysis(id){const item=itemFor(id);if(!item)return;activeImageId=id;if(imageSession?.itemId!==id)imageSession=null;renderImageDialog();$("imageDialog").showModal()}
function imageFieldRow(item,key,label){const candidate=item.imageAnalysisResult.fields[key],known=candidate.value!==Image.UNKNOWN;const priceOnly=key==="price";return `<div class="image-field-row"><div><strong>${label}</strong><small>AI 候选：${safeText(candidate.value)}</small><small>依据：${safeText(candidate.evidence)}</small></div>${priceOnly?`<span class="small-note">售价请在定价面板人工填写</span>`:`<input type="text" data-image-value="${key}" value="${known?safeText(candidate.value):""}" placeholder="${known?"核对或修改":"不明；可人工填写"}" aria-label="人工确认${label}"><label><input type="checkbox" data-image-apply="${key}" ${known?"":"disabled"}>采用</label>`}</div>`}
function renderImageDialog(){const item=itemFor(activeImageId);if(!item)return;$("imageTitle").textContent=`图片分析 · ${item.sku||"未编号"}`;const current=imageSession?.itemId===item.id?imageSession:null;const result=item.imageAnalysisResult;$("imageContent").innerHTML=`<p class="small-note">选择本机图片后先预览；只有点击“分析图片”才会将图片发送至已配置的 Gemini API。不确定的候选显示“不明”，所有字段均需人工确认。支持 JPG、PNG、WebP，单张最多 8 MB。</p><label class="stacked">商品图片<input id="imageFile" type="file" accept="image/jpeg,image/png,image/webp"></label>${current?`<div class="image-preview"><img src="${safeText(current.dataUrl)}" alt="待分析商品图片"><span>${safeText(current.file.name)}</span></div>`:""}<div class="research-actions"><button id="analyzeImage" class="primary" ${current&&state.aiSettings.enabled?"":"disabled"}>分析图片</button><button id="openImageGemini">打开 Gemini 手动分析</button></div><p id="imageStatus" role="status">${state.aiSettings.enabled?"等待人工点击分析。":"Gemini API 当前关闭；请在设置中开启，或到 Gemini 手动上传图片。"}</p>${result?`<section class="image-results"><h3>候选字段 · ${safeText(result.fileName||"已分析图片")}</h3><p class="small-note">勾选并核对后，点击“采用所选字段”。未勾选字段保持原值；“不明”不会写入商品。</p><div class="image-field-list">${Image.FIELDS.map(([key,label])=>imageFieldRow(item,key,label)).join("")}</div>${result.observations.length?`<p><strong>可见信息：</strong>${safeText(result.observations.join("；"))}</p>`:""}${result.warnings.length?`<p><strong>待核对：</strong>${safeText(result.warnings.join("；"))}</p>`:""}<button id="applyImageFields" class="primary">采用所选字段</button></section>`:""}<p class="small-note">只保存分析文字结果，不保存原图。刷新后如需重看图片，请重新选择文件。</p>`}
$("closeImage").onclick=()=>$("imageDialog").close();
function fileAsDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error("图片读取失败"));reader.readAsDataURL(file)})}
$("imageContent").addEventListener("change",async event=>{if(event.target.id!=="imageFile")return;const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>8*1024*1024){$("imageStatus").textContent="请选择不超过 8 MB 的 JPG、PNG 或 WebP 图片。";return}const id=activeImageId;try{const dataUrl=await fileAsDataUrl(file);if(activeImageId!==id)return;imageSession={itemId:id,file,dataUrl};renderImageDialog()}catch(error){$("imageStatus").textContent=error.message}});
$("imageContent").addEventListener("input",event=>{const field=event.target.dataset.imageValue;if(!field)return;const checkbox=$("imageContent").querySelector(`[data-image-apply="${field}"]`);if(checkbox){checkbox.disabled=!event.target.value.trim()||event.target.value.trim()===Image.UNKNOWN;if(checkbox.disabled)checkbox.checked=false}});
$("imageContent").addEventListener("click",async event=>{const id=event.target.id;if(id==="analyzeImage")await analyzeImage();else if(id==="openImageGemini")window.open("https://gemini.google.com/app","_blank","noopener,noreferrer");else if(id==="applyImageFields")applyImageFields()});
async function analyzeImage(){const item=itemFor(activeImageId),current=imageSession;if(!item||!current||current.itemId!==item.id||!state.aiSettings.enabled)return;const key=getApiKey(),model=state.aiSettings.model.trim().replace(/^models\//,"");if(!key||!model){$("imageStatus").textContent="请先在设置中填写 Gemini 模型名称和 API Key。";return}const button=$("analyzeImage"),status=$("imageStatus");button.disabled=true;status.textContent="正在分析图片；不会自动修改商品字段……";const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),60000);try{const base64=current.dataUrl.split(",",2)[1];if(!base64)throw Error("图片数据无效");const body=Image.requestBody(item,current.file.type,base64);const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify(body),signal:controller.signal});if(!response.ok)throw Error(`HTTP ${response.status}`);const result=Image.parseResponse(await response.json());result.fileName=current.file.name;result.analyzedAt=new Date().toISOString();item.imageAnalysisResult=result;persist();if(activeImageId===item.id){renderImageDialog();$("imageStatus").textContent="分析完成。请逐项核对并选择要采用的字段。"}}catch(error){console.warn("Image analysis failed",error);status.textContent=`图片分析失败（${error.message}）。图片仍在本机；可打开 Gemini 手动分析。`;button.disabled=false}finally{clearTimeout(timeout)}}
function applyImageFields(){const item=itemFor(activeImageId);if(!item?.imageAnalysisResult)return;const checked=[...$("imageContent").querySelectorAll("[data-image-apply]:checked")];if(!checked.length){$("imageStatus").textContent="请先勾选至少一个已经人工核对的字段。";return}const changes={};try{for(const box of checked){const key=box.dataset.imageApply;const input=$("imageContent").querySelector(`[data-image-value="${key}"]`);const patch=Image.resolveChange(key,input?.value,state.options);if(!patch)throw Error(`${key} 尚未填写确认值`);Object.assign(changes,patch)}}catch(error){$("imageStatus").textContent=`未应用：${error.message}`;return}Object.assign(item,changes);Pricing.applyCalculation(item,state.pricingSettings);refresh();renderImageDialog();$("imageStatus").textContent=`已应用 ${checked.length} 个经人工确认的字段。`}
renderRows();renderPreview();persist();
globalThis.JisenDesktop={getItems:()=>state.items,getState:()=>state,normalizeItem,normalizeState,replaceState:input=>{const old=state;state=normalizeState(input);renderRows();renderPreview();if(!persist()){state=old;renderRows();renderPreview();throw Error("电脑本地数据保存失败")}},replaceItems:items=>{const old=state.items;state.items=items;renderRows();renderPreview();if(!persist()){state.items=old;renderRows();renderPreview();throw Error("电脑本地数据保存失败")}},setReviewFilter:value=>{reviewOnly=!!value;renderRows()},refresh,getPricingSettings:()=>state.pricingSettings};




