"use strict";
(function(){
  const V=globalThis.JisenVision,S=globalThis.JisenStore,C=globalThis.JisenCapture,P=globalThis.PricingAssistant,config=globalThis.JisenAIConfig;
  const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const labels={main:"主体",mark:"底款",box:"共箱",condition:"瑕疵",other:"其他"};
  let settings={enabled:false,url:config.AI_PROXY_URL,model:""},token="",photos=[],urls=[],mode="vision",target=null,busy=false,request=null;
  const bridge=()=>globalThis.JisenMobileBridge;
  function status(text){$("visionStatus").textContent=text;}
  function release(){urls.forEach(url=>URL.revokeObjectURL(url));urls=[];}
  async function load(){settings={...settings,...await S.getSetting("aiProxySettings")};token=await S.getSetting("aiProxyToken")||"";}
  async function renderSettings(){await load();const container=$("aiVisionSettings");if(!container)return;container.innerHTML=`<section class="card"><h3>AI Vision Assist</h3><label class="check"><input id="visionEnabled" type="checkbox" ${settings.enabled?"checked":""}>ON · 启用视觉辅助（默认 OFF）</label><label class="field">Proxy URL<input id="visionProxyUrl" type="url" value="${esc(settings.url)}" placeholder="https://xxx.workers.dev"></label><label class="field">Proxy Access Token<input id="visionProxyToken" type="password" autocomplete="off" value="${esc(token)}"></label><p class="small">Token 仅保存在本机 IndexedDB，不进入商品 ZIP 或备份。Gemini Key 仅存在 Cloudflare Secret。</p><p>当前模型：<span id="visionModel">${esc(settings.model||"测试连接后显示")}</span></p><button id="testVisionConnection">测试AI连接</button><p id="visionConnectionStatus" role="status"></p></section>`;container.onchange=async event=>{try{if(event.target.id==="visionEnabled")settings.enabled=event.target.checked;if(event.target.id==="visionProxyUrl")settings.url=event.target.value.trim().replace(/\/$/,"");if(event.target.id==="visionProxyToken"){token=event.target.value.trim();await S.putSetting("aiProxyToken",token);}await S.putSetting("aiProxySettings",settings);await refreshButton();}catch{$("visionConnectionStatus").textContent="设置保存失败，请检查本地存储";}};$("testVisionConnection").onclick=async event=>{event.target.disabled=true;try{$("visionConnectionStatus").textContent="正在检查Gemini模型和代理连接…";const data=await send("/api/health",{},()=>{});settings.model=data.model;await S.putSetting("aiProxySettings",settings);$("visionModel").textContent=data.model;$("visionConnectionStatus").textContent="Gemini Vision可用";}catch(error){$("visionConnectionStatus").textContent=`AI暂时不可用：${error.message}`;}finally{event.target.disabled=false;}};}
  async function refreshButton(){const product=bridge()?.current();if(!product||!$("mobileVision"))return;const id=product.recordId;const list=await S.photosForRecord(id);if(bridge().current()?.recordId!==id)return;$("mobileVision").disabled=list.length===0;$("mobileVisionHint").textContent=list.length?"将发送本次选择的照片用于AI识别。":"请先拍摄或选择照片。";}
  async function compressedImage(photo){let blob=photo.blob;if(blob.size>config.maxImageBytes||blob.type!=="image/jpeg"){const url=URL.createObjectURL(blob);let image;try{image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error("图片无法读取"));img.src=url;});}finally{URL.revokeObjectURL(url);}for(const [dimension,quality] of [[1600,.8],[1400,.7],[1100,.65],[900,.6]]){const scale=Math.min(1,dimension/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",quality));if(blob&&blob.size<=config.maxImageBytes)break;}}
    if(!blob||blob.size>config.maxImageBytes)throw Error("图片压缩后仍超过1MB，请选择较小图片");const bytes=new Uint8Array(await blob.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return {role:photo.slot,mimeType:blob.type,data:btoa(binary)};
  }
  function endpoint(path){let url;try{url=new URL(settings.url)}catch{throw Error("请在设置中填写Proxy URL")};if(url.protocol!=="https:"||url.username||url.password||url.search||url.hash)throw Error("Proxy URL必须是无凭据的HTTPS地址");return url.origin+url.pathname.replace(/\/$/,"")+path;}
  function send(path,body,onProgress){if(!token)throw Error("请在设置中填写Proxy Access Token");const url=endpoint(path);return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();request=xhr;xhr.open("POST",url);xhr.setRequestHeader("Content-Type","application/json");xhr.setRequestHeader("Authorization",`Bearer ${token}`);xhr.timeout=config.timeoutMs;xhr.upload.onprogress=event=>onProgress(event.lengthComputable?`正在上传图片 ${Math.round(event.loaded/event.total*100)}%`:"正在上传图片");xhr.upload.onload=()=>onProgress(mode==="research"?"正在深度调查":"正在识别");xhr.onload=()=>{request=null;try{const payload=JSON.parse(xhr.responseText);if(xhr.status<200||xhr.status>=300)throw Error(payload.error?.message||`HTTP ${xhr.status}`);resolve(payload);}catch(error){reject(error)}};xhr.onerror=()=>{request=null;reject(Error("代理网络不可用或CORS不允许此来源"))};xhr.ontimeout=()=>{request=null;reject(Error("AI请求超时，可以重试"))};xhr.onabort=()=>{request=null;reject(Error("已取消AI请求"))};xhr.send(JSON.stringify(body));});}
  async function open(nextMode="vision"){if(busy)return;target=bridge().current();if(!target)return;mode=nextMode;await load();photos=await S.photosForRecord(target.recordId);release();$("visionTitle").textContent=mode==="research"?"AI深度研究":"AI辅助识别";$("visionContent").innerHTML=`<p>AI建议 ≠ 已确认事实。所有采用操作均需人工核对。</p><p class="small">这些照片仅在本次AI分析时发送给Gemini。默认拍摄和保存完全本地。</p>${target.visionConfirmedFields||target.identityConfirmedAt?"<p class=notice>已有人工确认结果。新AI结果只作为新的建议。</p>":""}<div class="vision-photo-list">${photos.map((photo,index)=>{const url=URL.createObjectURL(photo.blob);urls.push(url);return `<label class="vision-photo"><input type="checkbox" data-vision-photo="${index}" checked><img src="${url}" alt="${labels[photo.slot]}"><span>${labels[photo.slot]} · ${Math.round(photo.blob.size/1024)}KB</span></label>`}).join("")||"<p>暂无照片，请先添加照片。</p>"}</div>${mode==="research"?`<p class="notice">仅对异常件主动研究；至少选1张。搜索可能增加成本。</p><label class="check"><input id="visionGrounding" type="checkbox">启用 Google Search Grounding（二级研究）</label><details><summary>人工调查 Prompt</summary><textarea id="manualVisionPrompt" rows="8" readonly>${esc(P.makePrompt(target,P.calculate(target,bridge().pricingSettings())))}</textarea><button id="copyVisionPrompt">复制 Prompt</button><button id="openVisionGemini">打开 Gemini</button></details>`:""}<button id="runVision" class="primary" ${photos.length?"":"disabled"}>${mode==="research"?"开始深度研究":"开始AI识别"}</button><p id="visionStatus" role="status"></p><div id="visionResults"></div>`;$("visionContent").onchange=()=>{const count=$("visionContent").querySelectorAll("[data-vision-photo]:checked").length;$("runVision").disabled=busy||count<1||count>5;status(count>5?"最多选择5张图片":count<1?"至少选择1张图片":"");};$("runVision").onclick=run;$("copyVisionPrompt")?.addEventListener("click",()=>navigator.clipboard.writeText($("manualVisionPrompt").value));$("openVisionGemini")?.addEventListener("click",()=>window.open("https://gemini.google.com/","_blank","noopener,noreferrer"));if(!$("mobileVisionDialog").open)$("mobileVisionDialog").showModal();if(mode==="vision"&&target.visionResult)renderVision();if(mode==="research"&&target.researchResult)renderResearch();}
  async function run(){if(busy)return;if(!settings.enabled){status("AI暂时不可用：请先在设置中开启AI Vision Assist。录入和保存不受影响。");return;}const selected=[...$("visionContent").querySelectorAll("[data-vision-photo]:checked")].map(input=>photos[Number(input.dataset.visionPhoto)]);if(selected.length<1||selected.length>5){status("请选择1～5张照片");return;}const product=target,requestMode=mode;busy=true;$("runVision").disabled=true;try{status("正在压缩所选图片…");const images=await Promise.all(selected.map(compressedImage));if(!$("mobileVisionDialog").open)throw Error("已取消AI请求");const productText={ruleSuggestedPrice:String(P.calculate(product,bridge().pricingSettings()).suggestedPrice)};for(const key of ["sku","objectType","itemType","customItemName","kiln","identityConfidence","identityEvidence","period","technique","artist","studio","accessories","condition","bottomMarkNote","boxNote","note"])if(product[key]!=null)productText[key]=String(product[key]);status("正在上传图片");const payload=await send(requestMode==="research"?"/api/research":"/api/analyze",{product:productText,images,...(requestMode==="research"?{visionResult:product.visionResult,grounding:$("visionGrounding").checked}:{})},status);status("正在整理结果");const result=requestMode==="research"?V.normalizeResearch(payload.result,payload.groundingUsed===true):V.normalizeVision(payload.result);if(typeof payload.model!=="string"||typeof payload.analysisTimestamp!=="string")throw Error("AI返回信息不完整");if(requestMode==="research"){product.researchResult=result;product.researchMetadata={analysisTimestamp:payload.analysisTimestamp,model:payload.model,groundingUsed:payload.groundingUsed===true,groundingMetadata:payload.groundingMetadata};}else product.visionResult=result;product.analysisTimestamp=payload.analysisTimestamp;product.model=payload.model;await S.putProduct(product);settings.model=payload.model;await S.putSetting("aiProxySettings",settings);if(target===product&&mode===requestMode){requestMode==="research"?renderResearch():renderVision();status("分析完成。字段和最终售价未被改动，请逐项确认。")}}catch(error){status(`AI暂时不可用：${error.message}。仍可保存商品、规则定价、导出ZIP和继续下一件。`);}finally{busy=false;$("runVision").disabled=false;}}
  function renderVision(){const r=target.visionResult;if(!r)return;$("visionResults").innerHTML=`<h3>AI辅助识别结果</h3><p>${esc(r.summary)}</p><p>建议等级：${esc(r.recommendedConfidence)}（尚未采用）</p><p>${esc(r.visualHighlights.join("；"))}</p><p class="notice">不确定性：${esc(r.uncertainties.join("；")||"仍需人工核对照片未展示的部分")}</p><details><summary>底款 / 箱书 / 品相详细依据</summary><pre>${esc(JSON.stringify({markAssessment:r.markAssessment,boxAssessment:r.boxAssessment,conditionAssessment:r.conditionAssessment},null,2))}</pre></details>${V.suggestions(r).map(s=>`<div class="vision-field" data-suggestion="${s.key}"><strong>${esc(s.label)} · ${s.confidence}%</strong><p>建议：${esc(s.value)}<br>依据：${esc(s.evidence||"参见底款、箱书与视觉依据")}</p><input data-confirm-value="${s.key}" value="${V.known(s.value)?esc(s.value):""}" placeholder="不明；可人工修改" aria-label="人工确认${esc(s.label)}"><div class="row-actions"><button data-adopt-vision="${s.key}">采用</button><button data-edit-vision="${s.key}">修改</button><button data-ignore-vision="${s.key}">忽略</button></div><span data-adoption="${s.key}"></span></div>`).join("")}<button id="adoptSafeVision">采用安全建议</button><p class="small">仅器型、明确工艺、普通品相；不会采用作者、窑口、年代、身份、售价。已有值需逐项确认覆盖。</p><details><summary>单独人工确认身份等级</summary><label class="field">等级<select id="confirmVisionGrade">${Object.keys({D_UNKNOWN:1,C_STYLE:1,B_PROBABLE:1,A_CONFIRMED:1}).map(g=>`<option ${target.identityConfidence===g?"selected":""}>${g}</option>`).join("")}</select></label><label class="field">直接证据（A级必填）<input id="confirmVisionEvidence" value="${esc(target.identityEvidence||"")}" placeholder="人工核对的箱书、陶印或官方标签"></label><button id="adoptVisionGrade">确认此身份等级</button><p>等级确认后仍需在定价因素中人工勾选加价项。风格窑口不会自动触发加价。</p></details><p>${esc(V.researchReasons(target,r,P.calculate(target,bridge().pricingSettings())).join("；")||"普通件无额外研究建议")}</p><button id="visionGoResearch">${V.researchReasons(target,r,P.calculate(target,bridge().pricingSettings())).length?"建议深度调查":"手动深度调查"}</button>`;
    $("visionResults").onclick=async event=>{const el=event.target;try{if(el.dataset.editVision){const input=$(`visionResults`).querySelector(`[data-confirm-value="${el.dataset.editVision}"]`);input.focus();input.select();return;}if(el.dataset.ignoreVision){$(`visionResults`).querySelector(`[data-adoption="${el.dataset.ignoreVision}"]`).textContent="已忽略，原字段保持";return;}if(el.dataset.adoptVision){await adopt(el.dataset.adoptVision);return;}if(el.id==="adoptSafeVision"){for(const suggestion of V.suggestions(r).filter(s=>s.safe)){if(fieldValue(target,suggestion.key)){continue;}await adopt(suggestion.key);}status("空字段中的安全建议已采用；已有人工信息和高风险字段保留。");}if(el.id==="adoptVisionGrade"){V.confirmIdentity(target,$("confirmVisionGrade").value,$("confirmVisionEvidence").value);await persistHuman();status("人工身份等级已确认，售价未改动。");}if(el.id==="visionGoResearch")await open("research");}catch(error){status(`未采用：${error.message}`);}};
  }
  function fieldValue(product,key){return key==="itemType"&&product.itemType==="自定义"?product.customItemName:product[key];}
  async function persistHuman(){target.updatedAt=new Date().toISOString();P.applyCalculation(target,bridge().pricingSettings());await S.putProduct(target);if(bridge().current()?.recordId===target.recordId)bridge().refresh();}
  async function adopt(key){const value=$("visionResults").querySelector(`[data-confirm-value="${key}"]`).value;if(fieldValue(target,key)&&fieldValue(target,key)!==value&&!confirm(`当前${key}已有人工信息「${fieldValue(target,key)}」，确认用已核对的「${value}」替换？`))return;V.confirmField(target,key,value,target.visionResult);await persistHuman();$("visionResults").querySelector(`[data-adoption="${key}"]`).textContent=`已人工采用：${fieldValue(target,key)}`;}
  function renderResearch(){const r=target.researchResult;if(!r)return;$("visionResults").innerHTML=`<h3>AI研究资料 · 仅供人工参考</h3><p>${esc(r.identityAssessment)}</p><p>作者：${esc(r.artistAssessment)}<br>箱书：${esc(r.boxAssessment)}</p><p>规则建议：¥${P.calculate(target,bridge().pricingSettings()).suggestedPrice}<br>AI零售区间：${esc(r.recommendedRetailRange.currency)} ${r.recommendedRetailRange.min}–${r.recommendedRetailRange.max}<br>${esc(r.recommendedRetailRange.notes)}</p><h4>实际成交 / 类似成交</h4><pre>${esc(JSON.stringify(r.soldComparables,null,2))}</pre><h4>挂牌价（不是成交价）</h4><pre>${esc(JSON.stringify(r.askingPrices,null,2))}</pre><h4>其他市场证据</h4><pre>${esc(JSON.stringify(r.marketEvidence.filter(v=>v.status==="UNKNOWN"),null,2))}</pre><p>风险：${esc(r.riskFlags.join("；"))}</p><h4>可核查来源</h4>${r.sources.map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.url)}</a></p>`).join("")||"<p>无可核查来源</p>"}<div id="visionSearchAttribution"></div><label class="field">人工最终售价 ¥<input id="visionFinalPrice" type="number" min="0" step="0.01" value="${esc(target.price)}"></label><button id="adoptVisionFinalPrice">采用最终售价</button><p class="small">不会把AI区间自动填入此输入框；需你人工填写并点击采用。</p>`;
    const metadata=target.researchMetadata?.groundingMetadata;if(metadata?.searchEntryPoint?.renderedContent){const frame=document.createElement("iframe");frame.title="Google Search 来源归属";frame.setAttribute("sandbox", "allow-popups");frame.referrerPolicy="no-referrer";frame.srcdoc=metadata.searchEntryPoint.renderedContent;$("visionSearchAttribution").append(frame);}
    $("adoptVisionFinalPrice").onclick=async()=>{const value=$("visionFinalPrice").value;if(value===""||!Number.isFinite(Number(value))||Number(value)<0){status("请输入有效的人工最终售价");return;}target.price=value;target.finalPrice=value;await persistHuman();status("已采用人工最终售价。");};
  }
  $("mobileVision").onclick=()=>open().catch(error=>status(error.message));$("closeVision").onclick=()=>$("mobileVisionDialog").close();$("mobileVisionDialog").addEventListener("close",()=>{request?.abort();release();});
  globalThis.JisenVisionUI={renderSettings,refreshButton,openResearch:()=>open("research"),compressedImage};
})();
