"use strict";
const Capture=globalThis.JisenCapture,Store=globalThis.JisenStore,Pricing=globalThis.PricingAssistant;
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const money=n=>`¥${new Intl.NumberFormat("zh-CN").format(Number(n)||0)}`;
const STATUS_NAME={DRAFT:"未完成",READY:"待导出",REVIEW:"待老板审核",EXPORTED:"已导出",APPROVED:"已确认"};
const IDENTITY={A_CONFIRMED:"A｜确认",B_PROBABLE:"B｜高概率",C_STYLE:"C｜风格判断",D_UNKNOWN:"D｜未知"};
let batch=null,deviceId="",current=null,lastProduct=null,pricingSettings=Pricing.defaultSettings(),saveTimer=null;
let mobileAi={enabled:false,model:"",rememberKey:false};
const photoLabels={main:"主体",mark:"底款",box:"共箱",condition:"瑕疵",other:"其他"};
let photoUrls=[];
function releasePhotoUrls(){for(const url of photoUrls)URL.revokeObjectURL(url);photoUrls=[]}
async function renderPhotos(){if(!current)return;const recordId=current.recordId;const photos=await Store.photosForRecord(recordId);if(current?.recordId!==recordId)return;releasePhotoUrls();$("photoSlots").innerHTML=Capture.PHOTO_SLOTS.map(slot=>{const entries=photos.filter(p=>p.slot===slot);return `<div class="photo-slot"><strong>${photoLabels[slot]}</strong><div class="photo-thumbs">${entries.map(photo=>{const url=URL.createObjectURL(photo.blob);photoUrls.push(url);return `<div class="photo-thumb"><button class="photo-open" data-photo-open="${escapeHtml(photo.photoId)}" aria-label="查看${photoLabels[slot]}"><img src="${url}" alt="${photoLabels[slot]}"></button><button data-photo-delete="${escapeHtml(photo.photoId)}" class="danger">删除</button></div>`}).join("")}</div><div class="row-actions"><label class="photo-picker">拍照<input type="file" accept="image/*" capture="environment" data-photo-slot="${slot}"></label><label class="photo-picker">从图库选择<input type="file" accept="image/*" data-photo-slot="${slot}" ${slot==="other"?"multiple":""}></label></div></div>`}).join("")}
async function compressPhoto(file,slot){if(!file.type.startsWith("image/"))throw Error("请选择图片文件");const image=await new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error("图片无法读取"))};img.src=url});const max=slot==="mark"||slot==="box"?2000:1600;const scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.84));if(!blob)throw Error("图片压缩失败");return blob}
$("photoSlots").addEventListener("change",async event=>{const input=event.target.closest("[data-photo-slot]");if(!input||!current)return;const recordId=current.recordId,slot=input.dataset.photoSlot;try{for(const file of input.files){const blob=await compressPhoto(file,slot);const existing=slot==="other"?[]:(await Store.photosForRecord(recordId)).filter(p=>p.slot===slot);await Store.putPhoto({photoId:Capture.uuid(),recordId,slot,blob,mimeType:"image/jpeg",createdAt:new Date().toISOString()});for(const photo of existing)await Store.deletePhoto(photo.photoId)}if(current.recordId===recordId)await renderPhotos();setStatus("captureStatusMessage","照片已压缩并保存在本机") }catch(error){setStatus("captureStatusMessage",`照片保存失败：${error.message}`)}});
$("photoSlots").addEventListener("click",async event=>{const deleteButton=event.target.closest("[data-photo-delete]");if(deleteButton){if(!confirm("删除这张本地照片？"))return;await Store.deletePhoto(deleteButton.dataset.photoDelete);await renderPhotos();return}const openButton=event.target.closest("[data-photo-open]");if(openButton){const photo=(await Store.photosForRecord(current.recordId)).find(p=>p.photoId===openButton.dataset.photoOpen);if(!photo)return;$("largePhoto").src=URL.createObjectURL(photo.blob);$("mobilePhotoDialog").showModal()}});
$("closePhoto").onclick=()=>{URL.revokeObjectURL($("largePhoto").src);$("largePhoto").removeAttribute("src");$("mobilePhotoDialog").close()};
function show(view){for(const id of ["homeView","captureView","batchView","mobileSettingsView"])$(id).hidden=id!==view;window.scrollTo(0,0)}
function fieldSelect(key,label,options){const raw=key==="itemType"&&current.itemType==="自定义"?current.customItemName:current[key];const custom=(key==="itemType"&&current.itemType==="自定义")||!!raw&&!options.includes(raw);return `<label class="field">${label}<select data-field="${key}"><option value="">请选择</option>${options.map(v=>`<option value="${escapeHtml(v)}" ${raw===v?"selected":""}>${escapeHtml(v)}</option>`).join("")}<option value="__custom__" ${custom?"selected":""}>自定义</option></select></label><label class="field ${custom?"":"hidden"}" data-custom-wrap="${key}">自定义${label}<input data-custom="${key}" value="${custom?escapeHtml(raw):""}" placeholder="请输入${label}"></label>`}
function renderForm(){if(!current)return;$("captureBatch").textContent=`批次 ${current.batchId} · ${STATUS_NAME[current.captureStatus]||"未完成"}`;$("captureBadge").textContent=STATUS_NAME[current.captureStatus]||"未完成";$("mSku").value=current.sku||"";$("mPrice").value=current.price||"";$("mNote").value=current.note||"";$("mOwnerReview").checked=!!current.ownerReviewRequired;
  $("basicFields").innerHTML=fieldSelect("itemType","器型",Capture.OPTIONS.itemType)+fieldSelect("kiln","窑口",Capture.OPTIONS.kiln)+`<label class="field">身份可信度<select data-field="identityConfidence">${Object.entries(IDENTITY).map(([v,name])=>`<option value="${v}" ${current.identityConfidence===v?"selected":""}>${name}</option>`).join("")}</select></label><p class="small">A：共箱、陶印、箱书等直接依据；B：依据较强但不完整；C：外观风格判断；D：无法确认。身份类加价仅 A/B 生效。</p>`+fieldSelect("period","年代",Capture.OPTIONS.period);
  const techniques=new Set((current.technique||"").split("・").filter(Boolean));const extra=[...techniques].filter(t=>!Capture.OPTIONS.technique.includes(t)).join("・");
  $("advancedFields").innerHTML=`<label class="field">工艺（可多选）</label><div class="factor-list">${Capture.OPTIONS.technique.map(v=>`<label><input type="checkbox" data-technique="${escapeHtml(v)}" ${techniques.has(v)?"checked":""}>${escapeHtml(v)}</label>`).join("")}</div><label class="field">其他工艺<input id="mTechniqueOther" value="${escapeHtml(extra)}" placeholder="用・分隔"></label><label class="field">作家<input data-field="artist" value="${escapeHtml(current.artist)}"></label><label class="field">窑元 / 工房<input data-field="studio" value="${escapeHtml(current.studio)}"></label>${fieldSelect("accessories","附件",Capture.OPTIONS.accessories)}${fieldSelect("condition","品相",Capture.OPTIONS.condition)}<label class="field">价签模板<select data-field="templateType">${Object.entries(Capture.TEMPLATE_NAMES).map(([v,name])=>`<option value="${v}" ${current.templateType===v?"selected":""}>${name}</option>`).join("")}</select></label><h3>定价因素</h3><div class="factor-list">${pricingSettings.factors.map(f=>`<label><input type="checkbox" data-factor="${escapeHtml(f.id)}" ${(current.pricingFactors||[]).includes(f.id)?"checked":""}>${escapeHtml(f.label)} +${f.steps}${f.identityRelated?"（需A/B）":""}</label>`).join("")}</div>`;
  renderPhotos().catch(error=>setStatus("captureStatusMessage",error.message));renderPrice()}
function renderPrice(){if(!current)return;const calc=Pricing.applyCalculation(current,pricingSettings);$("priceSummary").innerHTML=`基础 ${money(calc.pricingBase)} · 加价 +${calc.pricingScore} 档 · 品相 ${calc.review?"人工审核":`${calc.conditionAdjustment} 档`}<br><strong>建议 ${money(calc.suggestedPrice)}</strong>`;$("priceExplanation").innerHTML=`起点：${money(calc.baseUnrounded)} → 阶梯 ${money(calc.pricingBase)}。<br>计入：${calc.applied.map(f=>escapeHtml(f.label)).join("、")||"无"}。${calc.ignored.length?`<br>身份未确认，未计入：${calc.ignored.map(f=>escapeHtml(f.label)).join("、")}。`:""}${calc.review?"<br>品相需要人工审核。":""}`;$("reviewReasons").textContent=calc.researchRequired?`自动审核原因：${calc.researchReasons.join("；")}`:"普通商品无需审核。"}
function queueSave(){if(!current)return;current.updatedAt=new Date().toISOString();renderPrice();clearTimeout(saveTimer);const pending=current;saveTimer=setTimeout(async()=>{try{await Store.putProduct(pending);$("captureStatusMessage").textContent="草稿已保存在本机"}catch(error){$("captureStatusMessage").textContent=`保存失败：${error.message}`}},400)}
async function saveCurrent(){if(!current)return;clearTimeout(saveTimer);Pricing.applyCalculation(current,pricingSettings);current.captureStatus=Capture.statusFor(current);current.updatedAt=new Date().toISOString();await Store.putProduct(current);lastProduct={...current};$("captureBadge").textContent=STATUS_NAME[current.captureStatus];$("captureStatusMessage").textContent=`已保存：${STATUS_NAME[current.captureStatus]}`;return current}
async function startNew(copyPrevious=false){const previous=copyPrevious?lastProduct:null;current=Capture.newProduct(batch.batchId,deviceId,previous);await Store.putProduct(current);renderForm();show("captureView");$("captureStatusMessage").textContent=copyPrevious?"已复制上一件的器物信息；SKU、价格和照片为空。":"新商品已建立本地草稿。"}
async function openProduct(id){current=await Store.getProduct(id);if(!current)return;renderForm();show("captureView");$("captureStatusMessage").textContent=""}
async function refreshHome(){const products=(await Store.listProducts()).filter(p=>p.batchId===batch.batchId);$("homeBatch").textContent=batch.batchId;$("homeBatchTime").textContent=`创建：${new Date(batch.createdAt).toLocaleString("zh-CN")}`;$("statDraft").textContent=products.filter(p=>p.captureStatus==="DRAFT").length;$("statReview").textContent=products.filter(p=>p.captureStatus==="REVIEW").length;$("statReady").textContent=products.filter(p=>["READY","EXPORTED","APPROVED"].includes(p.captureStatus)).length;$("statTotal").textContent=products.length}
async function renderBatch(){const products=(await Store.listProducts()).filter(p=>p.batchId===batch.batchId).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));$("batchMeta").innerHTML=`<p>批次：<strong>${escapeHtml(batch.batchId)}</strong><br>创建：${escapeHtml(new Date(batch.createdAt).toLocaleString("zh-CN"))}<br>商品：${products.length} · 已完成：${products.filter(p=>["READY","EXPORTED","APPROVED"].includes(p.captureStatus)).length} · 审核：${products.filter(p=>p.captureStatus==="REVIEW").length}${batch.exportedAt?`<br>上次导出：${escapeHtml(new Date(batch.exportedAt).toLocaleString("zh-CN"))}`:""}</p>`;$("batchProducts").innerHTML=products.map(p=>`<div class="batch-item"><div><strong>${escapeHtml(p.sku||"未填 SKU")} · ${escapeHtml(p.itemType==="自定义"?p.customItemName:p.itemType||"未填器型")}</strong><small>${escapeHtml(STATUS_NAME[p.captureStatus]||p.captureStatus)} · ${escapeHtml(p.kiln||"窑口未填")}</small></div><button data-open-product="${escapeHtml(p.recordId)}">打开</button></div>`).join("")||"<p class=small>本批次还没有商品。</p>";show("batchView")}
function setStatus(id,message){$(id).textContent=message}
async function init(){try{await Store.open();deviceId=await Store.getSetting("deviceId")||Capture.uuid();await Store.putSetting("deviceId",deviceId);pricingSettings=Pricing.normalizeSettings(await Store.getSetting("pricingSettings"));mobileAi=await Store.getSetting("aiSettings")||mobileAi;const id=await Store.getSetting("currentBatchId");batch=id?await Store.getBatch(id):null;if(!batch||batch.endedAt){const all=await Store.listBatches();batch={batchId:Capture.batchIdFor(new Date(),all),deviceId,createdAt:new Date().toISOString(),endedAt:null,exportedAt:null};await Store.putBatch(batch);await Store.putSetting("currentBatchId",batch.batchId)}await refreshHome();show("homeView")}catch(error){setStatus("homeStatus",`无法打开本地数据库：${error.message}。请用手机浏览器的 HTTPS 静态网页地址打开，并允许本地存储。`)}}
$("newProduct").onclick=()=>startNew().catch(error=>setStatus("homeStatus",error.message));
$("copyPrevious").onclick=async()=>{try{if(!lastProduct){const products=(await Store.listProducts()).filter(p=>p.batchId===batch.batchId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));lastProduct=products[0]||null}if(!lastProduct){setStatus("homeStatus","本批次还没有可复制的商品信息");return}await startNew(true)}catch(error){setStatus("homeStatus",error.message)}};
$("continueDraft").onclick=async()=>{const drafts=(await Store.listProducts()).filter(p=>p.batchId===batch.batchId&&p.captureStatus==="DRAFT").sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));if(drafts.length)await openProduct(drafts[0].recordId);else setStatus("homeStatus","本批次没有未完成商品。")};
$("openBatch").onclick=()=>renderBatch();$("openMobileSettings").onclick=()=>renderMobileSettings();
document.addEventListener("click",event=>{const go=event.target.closest("[data-go]");if(go?.dataset.go==="home")refreshHome().then(()=>show("homeView"));const product=event.target.closest("[data-open-product]");if(product)openProduct(product.dataset.openProduct)});
function fieldChange(event){if(!current)return;const el=event.target;if(el.dataset.field){const key=el.dataset.field;if(el.tagName==="SELECT"&&el.value==="__custom__"){const wrap=document.querySelector(`[data-custom-wrap="${key}"]`);wrap.classList.remove("hidden");current[key]=key==="itemType"?"自定义":"";if(key==="itemType")current.customItemName="";wrap.querySelector("input").focus()}else{current[key]=el.value;if(key==="itemType")current.customItemName="";const wrap=document.querySelector(`[data-custom-wrap="${key}"]`);if(wrap)wrap.classList.add("hidden")}}else if(el.dataset.custom){if(el.dataset.custom==="itemType"){current.itemType="自定义";current.customItemName=el.value}else current[el.dataset.custom]=el.value}else if(el.dataset.factor){const set=new Set(current.pricingFactors);el.checked?set.add(el.dataset.factor):set.delete(el.dataset.factor);current.pricingFactors=[...set]}else if(el.dataset.technique||el.id==="mTechniqueOther"){const checks=[...$("advancedFields").querySelectorAll("[data-technique]:checked")].map(x=>x.dataset.technique);const other=$("mTechniqueOther").value.split("・").map(x=>x.trim()).filter(Boolean);current.technique=[...checks,...other].join("・")}else return;queueSave()}
$("basicFields").addEventListener("change",fieldChange);$("basicFields").addEventListener("input",fieldChange);$("advancedFields").addEventListener("change",fieldChange);$("advancedFields").addEventListener("input",fieldChange);
$("mSku").addEventListener("input",e=>{current.sku=e.target.value;queueSave()});$("mPrice").addEventListener("input",e=>{current.price=e.target.value;queueSave()});$("mNote").addEventListener("input",e=>{current.note=e.target.value;queueSave()});$("mOwnerReview").addEventListener("change",e=>{current.ownerReviewRequired=e.target.checked;queueSave()});
$("useSuggested").onclick=()=>{if(!current)return;current.price=String(Pricing.calculate(current,pricingSettings).suggestedPrice);$("mPrice").value=current.price;queueSave()};
$("saveCapture").onclick=()=>saveCurrent().catch(error=>setStatus("captureStatusMessage",error.message));
$("saveNext").onclick=async()=>{try{await saveCurrent();await startNew()}catch(error){setStatus("captureStatusMessage",error.message)}};
async function createBatch(){const all=await Store.listBatches();batch={batchId:Capture.batchIdFor(new Date(),all),deviceId,createdAt:new Date().toISOString(),endedAt:null,exportedAt:null};await Store.putBatch(batch);await Store.putSetting("currentBatchId",batch.batchId);await renderBatch()}
$("newBatch").onclick=async()=>{if(confirm("新建批次？当前批次中的商品会保留。"))await createBatch()};
$("endBatch").onclick=async()=>{if(!confirm("结束当前批次并开始新批次？"))return;batch.endedAt=new Date().toISOString();await Store.putBatch(batch);await createBatch()};
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function exportCurrentBatch(target){try{setStatus(target,"正在生成 ZIP…");const products=(await Store.listProducts()).filter(p=>p.batchId===batch.batchId);const photos=(await Store.listPhotos()).filter(p=>products.some(item=>item.recordId===p.recordId));const result=await JisenTransfer.exportBatch(batch,products,photos,deviceId);downloadBlob(result.blob,`JISEN_CERAMICS_${batch.batchId.replace(/-/g,"_")}.zip`);const stamp=result.manifest.exportedAt;for(const product of products){product.exportedAt=stamp;if(product.captureStatus==="READY")product.captureStatus="EXPORTED";await Store.putProduct(product)}batch.exportedAt=stamp;await Store.putBatch(batch);setStatus(target,`ZIP 已生成：${products.length} 件、${photos.length} 张照片。原始商品仍保留。`);await refreshHome()}catch(error){setStatus(target,`导出失败：${error.message}`)}}
$("exportBatch").onclick=()=>exportCurrentBatch("homeStatus");$("batchExport").onclick=()=>exportCurrentBatch("batchStatus");
function getMobileKey(){try{return (mobileAi.rememberKey?localStorage:sessionStorage).getItem("jisen-mobile-gemini-key")||""}catch{return ""}}
function setMobileKey(key){try{(mobileAi.rememberKey?localStorage:sessionStorage).setItem("jisen-mobile-gemini-key",key);(mobileAi.rememberKey?sessionStorage:localStorage).removeItem("jisen-mobile-gemini-key")}catch{throw Error("API Key 保存失败")}}
async function renderMobileSettings(){const products=await Store.listProducts(),photos=await Store.listPhotos();$("mobileSettingsContent").innerHTML=`<section class="card"><h3>本地数据</h3><p>商品数据和照片默认仅保存在本设备浏览器中，不会自动上传云端。</p><p>使用 Gemini AI 调查时，仅会上传用户本次主动选择的数据和图片。</p><p>本机：${products.length} 件商品、${photos.length} 张照片。请定期导出备份；清除浏览器数据会删除本地资料。</p><button id="backupAll">导出所有数据备份</button><label class="photo-picker">恢复本地备份<input id="restoreBackup" type="file" accept=".zip,application/zip"></label><p id="backupStatus" role="status"></p></section><section class="card"><h3>Gemini 调查（默认关闭）</h3><label class="check"><input id="mobileAiEnabled" type="checkbox" ${mobileAi.enabled?"checked":""}>启用 API 模式</label><label class="field">模型 ID<input id="mobileAiModel" value="${escapeHtml(mobileAi.model)}" placeholder="填写当前可用模型"></label><label class="field">API Key<input id="mobileAiKey" type="password" autocomplete="off" value="${escapeHtml(getMobileKey())}"></label><label class="check"><input id="mobileRememberKey" type="checkbox" ${mobileAi.rememberKey?"checked":""}>在本机记住 Key（默认仅会话）</label><p class="small">Key 不进入 ZIP 备份，也不会随商品导出。</p></section>`;show("mobileSettingsView")}
$("mobileSettingsContent").addEventListener("change",async event=>{const el=event.target;if(el.id==="restoreBackup"){const file=el.files?.[0];if(!file)return;try{setStatus("backupStatus","正在读取备份…");const data=await JisenTransfer.parseBackup(file);setStatus("backupStatus",`备份包含 ${data.products.length} 件商品、${data.photos.length} 张照片、${data.batches.length} 个批次。`);if(!confirm(`恢复备份会替换当前本机全部商品、照片、批次和设置。确认恢复 ${data.products.length} 件商品？`))return;await Store.replaceBackup(data);location.reload()}catch(error){setStatus("backupStatus",`恢复失败：${error.message}`)}return}if(el.id==="mobileAiEnabled")mobileAi.enabled=el.checked;else if(el.id==="mobileAiModel")mobileAi.model=el.value.trim();else if(el.id==="mobileRememberKey"){const key=getMobileKey();mobileAi.rememberKey=el.checked;setMobileKey(key)}else if(el.id==="mobileAiKey")setMobileKey(el.value.trim());else return;await Store.putSetting("aiSettings",mobileAi)});
$("mobileSettingsContent").addEventListener("click",async event=>{if(event.target.id!=="backupAll")return;try{setStatus("backupStatus","正在生成备份…");const data={products:await Store.listProducts(),photos:await Store.listPhotos(),batches:await Store.listBatches(),settings:await Store.listSettings()};const blob=await JisenTransfer.exportBackup(data);downloadBlob(blob,"JISEN_CERAMICS_MOBILE_BACKUP.zip");setStatus("backupStatus",`备份已生成：${data.products.length} 件商品、${data.photos.length} 张照片。`)}catch(error){setStatus("backupStatus",`备份失败：${error.message}`)}});
async function researchView(){if(!current)return;const prompt=Pricing.makePrompt(current,Pricing.calculate(current,pricingSettings));const photos=(await Store.photosForRecord(current.recordId)).filter(p=>["main","mark","box","condition"].includes(p.slot));$("mobileResearchContent").innerHTML=`<p class="small">只在你点击调用时发送。图片研究会增加 API 使用量；结果仅作资料，不会自动修改商品字段或售价。</p><textarea id="mobilePrompt" rows="9">${escapeHtml(prompt)}</textarea><div class="row-actions"><button id="copyMobilePrompt">复制 Prompt</button><button id="openGeminiSite">打开 Gemini</button></div>${mobileAi.enabled?`<h3>API 调查</h3><p>选 1～4 张本地压缩图，可留空仅发送文字。</p>${photos.map(p=>`<label class="check"><input type="checkbox" data-research-photo="${escapeHtml(p.photoId)}">${photoLabels[p.slot]}</label>`).join("")}<button id="callMobileGemini">调用 Gemini</button>`:"<p>API 模式关闭；可复制 Prompt 人工调查。</p>"}<p id="mobileAiStatus" role="status"></p><pre>${escapeHtml(current.aiResearchResult?JSON.stringify(current.aiResearchResult,null,2):"暂无研究结果")}</pre>`;if(!$("mobileResearchDialog").open)$("mobileResearchDialog").showModal()}
$("mobileResearch").onclick=()=>researchView();$("closeMobileResearch").onclick=()=>$("mobileResearchDialog").close();
$("mobileResearchContent").addEventListener("click",async event=>{const id=event.target.id;if(id==="copyMobilePrompt"){await navigator.clipboard.writeText($("mobilePrompt").value);setStatus("mobileAiStatus","Prompt 已复制");return}if(id==="openGeminiSite"){window.open("https://gemini.google.com/","_blank","noopener,noreferrer");return}if(id!=="callMobileGemini")return;const key=getMobileKey(),model=mobileAi.model.trim().replace(/^models\//,"");if(!key||!model){setStatus("mobileAiStatus","请先在设置中填写模型 ID 和 API Key");return}const selected=[...$("mobileResearchContent").querySelectorAll("[data-research-photo]:checked")].map(el=>el.dataset.researchPhoto);if(selected.length>4){setStatus("mobileAiStatus","最多选择四张图片");return}event.target.disabled=true;try{const photos=await Store.photosForRecord(current.recordId),parts=[{text:$("mobilePrompt").value}];for(const id of selected){const photo=photos.find(p=>p.photoId===id);const bytes=new Uint8Array(await photo.blob.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));parts.push({inline_data:{mime_type:"image/jpeg",data:btoa(binary)}})}setStatus("mobileAiStatus","正在调查…");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000);let response;try{response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{parts}]}),signal:controller.signal})}finally{clearTimeout(timer)}if(!response.ok)throw Error(`HTTP ${response.status}`);const payload=await response.json(),result=payload.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("").trim();if(!result)throw Error("未返回可读取的文本");current.aiResearchResult={text:result,researchedAt:new Date().toISOString(),photoCount:selected.length};await Store.putProduct(current);await researchView();setStatus("mobileAiStatus","研究资料已保存，请人工核对") }catch(error){setStatus("mobileAiStatus",`调查失败：${error.message}。本地商品未受影响。`)}finally{event.target.disabled=false}});
if("serviceWorker" in navigator&&location.protocol==="https:")navigator.serviceWorker.register("service-worker.js").catch(error=>console.warn("Offline cache unavailable",error));
init();
