"use strict";
(function(){
  const $=id=>document.getElementById(id),Desktop=globalThis.JisenDesktop,Store=globalThis.JisenStore,Transfer=globalThis.JisenTransfer,Pricing=globalThis.PricingAssistant;
  const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  let pending=null,reviewId=null,photoUrls=[];
  const closeUrls=()=>{for(const url of photoUrls)URL.revokeObjectURL(url);photoUrls=[]};
  $("reviewFilter").onclick=()=>{const active=$("reviewFilter").classList.toggle("active");Desktop.setReviewFilter(active);$("reviewFilter").textContent=active?"显示全部商品":"待老板审核"};
  $("importMobileBtn").onclick=()=>$("importMobileFile").click();
  $("importMobileFile").onchange=async event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{pending=await Transfer.parseBatch(file);renderImport();$("mobileImportDialog").showModal()}catch(error){alert(`手机批次读取失败：${error.message}`)}};
  $("closeMobileImport").onclick=()=>$("mobileImportDialog").close();
  function conflicts(product,items){return JisenImportRules.classify(product,items)}
  function renderImport(){const items=Desktop.getItems(),products=pending.manifest.products;let fresh=0,duplicates=0,skus=0;const rows=products.map((product,index)=>{const {existing,kind}=conflicts(product,items);if(kind==="新商品")fresh++;else if(kind==="recordId 重复")duplicates++;else skus++;return `<tr><td>${esc(product.sku||"未填 SKU")}</td><td>${esc(kind)}</td><td>${esc(product.captureStatus||"READY")}</td><td>${existing?esc(existing.updatedAt||"无"):"—"}</td><td>${esc(product.updatedAt||"无")}</td><td><select data-import-choice="${index}"><option value="${existing?"skip":"new"}">${existing?"跳过":"作为新商品导入"}</option>${existing?'<option value="new">作为新记录导入</option><option value="overwrite">覆盖现有</option>':""}</select></td></tr>`}).join("");$("mobileImportContent").innerHTML=`<p>批次 <strong>${esc(pending.manifest.batchId)}</strong> · ${products.length} 件 · 新商品 ${fresh} · recordId 重复 ${duplicates} · SKU 冲突 ${skus} · 待老板审核 ${products.filter(p=>p.captureStatus==="REVIEW").length}</p><p>有冲突时默认跳过。覆盖业务数据需再次确认；照片默认合并。</p><div class="table-scroll"><table><thead><tr><th>SKU</th><th>判定</th><th>状态</th><th>电脑更新</th><th>手机更新</th><th>处理</th></tr></thead><tbody>${rows}</tbody></table></div><label><input id="replaceImportPhotos" type="checkbox">覆盖时替换原照片（默认合并）</label><div class="row-actions"><button id="importFreshOnly">全部导入无冲突新商品</button><button id="confirmMobileImport" class="primary">按所选处理导入</button></div><p id="mobileImportStatus" role="status"></p>`}
  $("mobileImportContent").addEventListener("click",async event=>{if(!["confirmMobileImport","importFreshOnly"].includes(event.target.id))return;const freshOnly=event.target.id==="importFreshOnly",items=Desktop.getItems(),actions=pending.manifest.products.map((product,index)=>{const conflict=conflicts(product,items);return {product,index,conflict,choice:freshOnly?(conflict.existing?"skip":"new"):$("mobileImportContent").querySelector(`[data-import-choice="${index}"]`).value}}).filter(a=>a.choice!=="skip");const overwrite=actions.filter(a=>a.choice==="overwrite");if(overwrite.length&&!confirm(`将覆盖 ${overwrite.length} 件电脑商品的业务数据。确认继续？`))return;const replacePhotos=$("replaceImportPhotos").checked;if(overwrite.length&&replacePhotos&&!confirm("替换照片会删除这些商品的原有本地照片。确认删除并替换？"))return;event.target.disabled=true;try{const next=[...items],photoWrites=[],photoDeletes=[],aiWrites=[];for(const action of actions){const {product,conflict,choice}=action;const destinationId=choice==="overwrite"?conflict.existing.recordId:choice==="new"&&conflict.existing?JisenCapture.uuid():product.recordId;const imported=Desktop.normalizeItem({...product,id:choice==="overwrite"?conflict.existing.id:destinationId,recordId:destinationId,photoCount:0});aiWrites.push({...product,recordId:destinationId});const related=pending.photos.filter(p=>p.recordId===product.recordId);if(choice==="overwrite"){const old=await Store.photosForRecord(destinationId);if(replacePhotos)photoDeletes.push(...old);imported.photoCount=(replacePhotos?0:old.length)+related.length;next[next.indexOf(conflict.existing)]=imported}else{imported.photoCount=related.length;next.push(imported)}for(const photo of related)photoWrites.push({...photo,photoId:JisenCapture.uuid(),recordId:destinationId})}for(const photo of photoWrites)await Store.putPhoto(photo);Desktop.replaceItems(next);for(const product of aiWrites)await Store.putProduct(product);for(const photo of photoDeletes)await Store.deletePhoto(photo.photoId);$("mobileImportStatus").textContent=`已导入 ${actions.length} 件；跳过 ${pending.manifest.products.length-actions.length} 件。`;renderImport()}catch(error){$("mobileImportStatus").textContent=`导入失败：${error.message}`}finally{event.target.disabled=false}});
  async function renderPhotos(recordId,container){closeUrls();const photos=await Store.photosForRecord(recordId);const names={main:"主体",mark:"底款",box:"共箱",condition:"瑕疵",other:"其他"};container.innerHTML=photos.length?photos.map(photo=>{const url=URL.createObjectURL(photo.blob);photoUrls.push(url);return `<figure class="pc-photo"><img src="${url}" alt="${names[photo.slot]||"照片"}"><figcaption>${names[photo.slot]||"照片"}</figcaption></figure>`}).join(""):"<p>本机没有该商品的照片。</p>"}
  $("itemRows").addEventListener("click",async event=>{const photo=event.target.closest("[data-photo-view]");if(photo){await renderPhotos(photo.dataset.photoView,$("pcPhotosContent"));$("pcPhotosDialog").showModal();return}const review=event.target.closest("[data-review-open]");if(review)await openReview(review.dataset.reviewOpen)});
  $("closePcPhotos").onclick=()=>{$("pcPhotosDialog").close();closeUrls()};
  $("pcZipBackup").onclick=async()=>{try{const zip=new JSZip(),state=Desktop.getState(),ids=new Set(state.items.map(p=>p.recordId)),photos=(await Store.listPhotos()).filter(p=>ids.has(p.recordId));const refs=[];for(const photo of photos){const path=`images/${JisenCapture.safeStem({recordId:photo.recordId})}_${photo.photoId.replace(/[^A-Za-z0-9_-]/g,"")}.jpg`;zip.file(path,await photo.blob.arrayBuffer());refs.push({photoId:photo.photoId,recordId:photo.recordId,slot:photo.slot,path,createdAt:photo.createdAt})}zip.file("pc-backup.json",JSON.stringify({formatVersion:2,createdAt:new Date().toISOString(),state,photoRefs:refs,aiProducts:(await Store.listProducts()).filter(p=>ids.has(p.recordId))},null,2));const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`JISEN_CERAMICS_PC_BACKUP_${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){alert(`ZIP 备份失败：${error.message}`)}};
  $("pcZipRestore").onclick=()=>$("pcZipRestoreFile").click();
  $("pcZipRestoreFile").onchange=async event=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const zip=await JSZip.loadAsync(file),entry=zip.file("pc-backup.json");if(!entry)throw Error("缺少 pc-backup.json");const backup=JSON.parse(await entry.async("string"));if(backup.formatVersion!==2||!Array.isArray(backup.state?.items)||!Array.isArray(backup.photoRefs))throw Error("备份格式无效");const photos=[];for(const ref of backup.photoRefs){if(!/^images\/[A-Za-z0-9_-]+\.jpg$/.test(ref.path)||!zip.file(ref.path))throw Error("备份照片缺失或路径无效");photos.push({photoId:ref.photoId,recordId:ref.recordId,slot:ref.slot,createdAt:ref.createdAt,blob:new Blob([await zip.file(ref.path).async("uint8array")],{type:"image/jpeg"}),mimeType:"image/jpeg"})}if(!confirm(`备份包含 ${backup.state.items.length} 件商品、${photos.length} 张照片。恢复会替换电脑商品和相关照片。确认继续？`))return;const oldItems=Desktop.getItems(),oldIds=new Set(oldItems.map(p=>p.recordId)),oldPhotos=(await Store.listPhotos()).filter(p=>oldIds.has(p.recordId));try{for(const photo of oldPhotos)await Store.deletePhoto(photo.photoId);for(const photo of photos)await Store.putPhoto(photo);Desktop.replaceState(backup.state);for(const product of backup.aiProducts||[])await Store.putProduct(product)}catch(error){for(const photo of photos)await Store.deletePhoto(photo.photoId);for(const photo of oldPhotos)await Store.putPhoto(photo);throw error}alert("电脑 ZIP 备份已恢复。") }catch(error){alert(`ZIP 恢复失败：${error.message}`)}};
  async function openReview(recordId){const item=Desktop.getItems().find(p=>p.recordId===recordId);if(!item)return;reviewId=recordId;$("mobileReviewTitle").textContent=`老板审核 · ${item.sku||"未填 SKU"}`;const ai=await Store.getProduct(recordId);const calc=Pricing.calculate(item,Desktop.getPricingSettings());$("mobileReviewContent").innerHTML=`<div id="reviewPhotos" class="pc-photo-grid"></div><p>员工判断：${esc(item.note||"无")}<br>身份可信度：${esc(item.identityConfidence)}<br>Gemini 研究：${esc(item.aiResearchResult?JSON.stringify(item.aiResearchResult):"无")}</p><details><summary>手机AI视觉 / 研究建议（仍需人工核对）</summary><pre>${esc(ai?.visionResult?JSON.stringify(ai.visionResult,null,2):"无视觉结果")}</pre><pre>${esc(ai?.researchResult?JSON.stringify(ai.researchResult,null,2):"无研究结果")}</pre></details><p>基础价 ¥${esc(calc.pricingBase)} · 加价 ${esc(calc.pricingScore)} 档 · 规则建议价 ¥${esc(calc.suggestedPrice)} · 手机暂定售价 ¥${esc(item.price)}</p><label>窑口<input data-review-field="kiln" value="${esc(item.kiln)}"></label><label>可信度<select data-review-field="identityConfidence">${["A_CONFIRMED","B_PROBABLE","C_STYLE","D_UNKNOWN"].map(v=>`<option value="${v}" ${item.identityConfidence===v?"selected":""}>${v}</option>`).join("")}</select></label><label>作者<input data-review-field="artist" value="${esc(item.artist)}"></label><label>定价因素</label><div class="review-factors">${Desktop.getPricingSettings().factors.map(f=>`<label><input type="checkbox" data-review-factor="${esc(f.id)}" ${(item.pricingFactors||[]).includes(f.id)?"checked":""}>${esc(f.label)}</label>`).join("")}</div><label>最终售价 ¥<input type="number" min="0" step="0.01" data-review-field="price" value="${esc(item.price)}"></label><label>模板<select data-review-field="templateType">${Object.entries(JisenCapture.TEMPLATE_NAMES).map(([v,n])=>`<option value="${esc(v)}" ${item.templateType===v?"selected":""}>${esc(n)}</option>`).join("")}</select></label><button id="approveMobileItem" class="primary">确认完成</button><p id="reviewStatus" role="status"></p>`;await renderPhotos(recordId,$("reviewPhotos"));$("mobileReviewDialog").showModal()}
  $("closeMobileReview").onclick=()=>{$("mobileReviewDialog").close();closeUrls()};
  $("mobileReviewContent").addEventListener("click",event=>{if(event.target.id!=="approveMobileItem")return;const item=Desktop.getItems().find(p=>p.recordId===reviewId);if(!item)return;const edits={};for(const el of $("mobileReviewContent").querySelectorAll("[data-review-field]"))edits[el.dataset.reviewField]=el.value;if(edits.price!==""&&(!Number.isFinite(Number(edits.price))||Number(edits.price)<0)){$("reviewStatus").textContent="请输入有效最终售价";return}Object.assign(item,edits);item.pricingFactors=[...$("mobileReviewContent").querySelectorAll("[data-review-factor]:checked")].map(el=>el.dataset.reviewFactor);item.captureStatus="APPROVED";item.updatedAt=new Date().toISOString();Desktop.refresh();$("mobileReviewDialog").close();closeUrls()});
})();
