"use strict";
(function(root){
  const Capture=root.JisenCapture;
  const SLOT_ORDER={main:0,mark:1,box:2,condition:3,other:4};
  const copy=value=>JSON.parse(JSON.stringify(value));
  function safeName(value){return String(value||"").replace(/[^A-Za-z0-9_-]/g,"-").replace(/-+/g,"-").replace(/^[-_]+|[-_]+$/g,"").slice(0,60)||"record"}
  async function assignPhotos(products,photos,zip){const used=new Set(),entries=[];for(const product of products){let stem=safeName(Capture.safeStem(product));if(used.has(stem))stem+=`_${safeName(product.recordId).slice(0,8)}`;used.add(stem);const refs=[];const related=photos.filter(p=>p.recordId===product.recordId).sort((a,b)=>(SLOT_ORDER[a.slot]??5)-(SLOT_ORDER[b.slot]??5)||String(a.createdAt).localeCompare(String(b.createdAt)));const counts={};for(const photo of related){const slot=Object.hasOwn(SLOT_ORDER,photo.slot)?photo.slot:"other";counts[slot]=(counts[slot]||0)+1;const suffix=counts[slot]>1||slot==="condition"||slot==="other"?`_${String(counts[slot]).padStart(2,"0")}`:"";const path=`images/${stem}_${slot}${suffix}.jpg`;zip.file(path,photo.blob instanceof Blob?await photo.blob.arrayBuffer():photo.blob);refs.push({photoId:photo.photoId,slot,path,createdAt:photo.createdAt||""})}entries.push({...copy(product),photoRefs:refs})}return entries}
  async function exportBatch(batch,products,photos,deviceId){if(!root.JSZip)throw Error("ZIP 库未加载");const zip=new root.JSZip(),exportedAt=new Date().toISOString();zip.folder("images");const entries=await assignPhotos(products,photos,zip);const manifest={formatVersion:2,appVersion:"2.0",batchId:batch.batchId,deviceId,createdAt:batch.createdAt,exportedAt,productCount:entries.length,products:entries};zip.file("manifest.json",JSON.stringify(manifest,null,2));zip.file("products.csv",Capture.csvFor(entries));return {blob:await zip.generateAsync({type:typeof window==="undefined"?"uint8array":"blob",compression:"DEFLATE"}),manifest}}
  async function readZip(file){if(!root.JSZip)throw Error("ZIP 库未加载");const zip=await root.JSZip.loadAsync(file);for(const path of Object.keys(zip.files))if(path.includes("..")||path.startsWith("/")||path.includes("\\"))throw Error("ZIP 包含不安全路径");return zip}
  async function parseBatch(file){const zip=await readZip(file);if(!zip.file("manifest.json")||!zip.file("products.csv"))throw Error("缺少 manifest.json 或 products.csv");const manifest=JSON.parse(await zip.file("manifest.json").async("string"));if(manifest.formatVersion!==2||!Array.isArray(manifest.products)||manifest.productCount!==manifest.products.length||!manifest.batchId)throw Error("批次清单格式无效");const csv=await zip.file("products.csv").async("string");if(!csv.startsWith("\uFEFF"))throw Error("CSV 缺少 UTF-8 BOM");const ids=new Set(),photos=[];for(const product of manifest.products){if(!product.recordId||ids.has(product.recordId)||!Array.isArray(product.photoRefs))throw Error("商品标识或照片引用无效");ids.add(product.recordId);for(const ref of product.photoRefs){if(!/^images\/[A-Za-z0-9_-]+\.jpg$/.test(ref.path)||!zip.file(ref.path)||!Object.hasOwn(SLOT_ORDER,ref.slot))throw Error("照片路径或槽位无效");photos.push({photoId:ref.photoId||Capture.uuid(),recordId:product.recordId,slot:ref.slot,blob:new Blob([await zip.file(ref.path).async("uint8array")],{type:"image/jpeg"}),mimeType:"image/jpeg",createdAt:ref.createdAt||""})}}return {manifest,photos,csv}}
  async function exportBackup(data){const zip=new root.JSZip();const products=await assignPhotos(data.products,data.photos,zip);const manifest={formatVersion:2,backup:true,appVersion:"2.0",createdAt:new Date().toISOString(),products,batches:copy(data.batches),settings:copy(data.settings.filter(entry=>!/[Tt]oken|[Kk]ey|[Ss]ecret/.test(entry.key)))};zip.file("backup.json",JSON.stringify(manifest,null,2));return zip.generateAsync({type:typeof window==="undefined"?"uint8array":"blob",compression:"DEFLATE"})}
  async function parseBackup(file){const zip=await readZip(file);const entry=zip.file("backup.json");if(!entry)throw Error("不是己森手机备份 ZIP");const manifest=JSON.parse(await entry.async("string"));if(manifest.formatVersion!==2||manifest.backup!==true||!Array.isArray(manifest.products)||!Array.isArray(manifest.batches)||!Array.isArray(manifest.settings))throw Error("备份格式无效");const photos=[];for(const product of manifest.products){if(!product.recordId||!Array.isArray(product.photoRefs))throw Error("备份商品无效");for(const ref of product.photoRefs){if(!/^images\/[A-Za-z0-9_-]+\.jpg$/.test(ref.path)||!zip.file(ref.path))throw Error("备份图片无效");photos.push({photoId:ref.photoId||Capture.uuid(),recordId:product.recordId,slot:ref.slot,blob:new Blob([await zip.file(ref.path).async("uint8array")],{type:"image/jpeg"}),mimeType:"image/jpeg",createdAt:ref.createdAt||""})}}return {products:manifest.products.map(({photoRefs,...p})=>p),photos,batches:manifest.batches,settings:manifest.settings}}
  root.JisenTransfer={exportBatch,parseBatch,exportBackup,parseBackup};
})(typeof window!=="undefined"?window:globalThis);
